/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Manage;

import DBConnect.DBconnect;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Umindu
 */
public class ShowGRNDetails extends javax.swing.JFrame {

    
    public ShowGRNDetails() {
        setUndecorated(true);
        initComponents();
    }
    
    public ShowGRNDetails(int GRNID) {
        setUndecorated(true);
        initComponents();
        
        //details load
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            statement.execute("select Date, SubTotal, Discount, VAT, GrandTotal FROM GRNDetails WHERE ID = '"+GRNID+"'");
            ResultSet resultSet = statement.getResultSet(); 
            if(resultSet.next()){
                grnID.setText("GRN No : "+GRNID);
                date.setText("Date : "+resultSet.getString("Date"));
                subTotal.setText("Sub Total : Rs. "+resultSet.getString("SubTotal"));
                discount.setText("Discount :  Rs. "+resultSet.getString("Discount"));
                vat.setText("VAT :             Rs. "+resultSet.getString("VAT"));
                grandTotal.setText("Grand Total : Rs. "+resultSet.getString("GrandTotal"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Manage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //table load
        JTableHeader header = GRNTable.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD , 14));
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            
            statement.execute("select ID, Name, UnitCost AS 'Unit Cost', Price, Qnt, ServiceUnit AS 'Service Unit', LotNo AS 'Lot No' FROM GRNProducts WHERE GRNID = '"+GRNID+"'");
            ResultSet resultSet = statement.getResultSet(); 
            
            GRNTable.setModel(DbUtils.resultSetToTableModel(resultSet));
        } catch (SQLException ex) {
            Logger.getLogger(Manage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        grnID = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GRNTable = new javax.swing.JTable();
        subTotal = new javax.swing.JLabel();
        discount = new javax.swing.JLabel();
        vat = new javax.swing.JLabel();
        grandTotal = new javax.swing.JLabel();
        doneButton = new button.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        grnID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        grnID.setText("GRN No : ");

        date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        date.setText("Date :");

        GRNTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(GRNTable);

        subTotal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        subTotal.setText("Sub Total : Rs.");

        discount.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        discount.setText("Discount :  Rs.");

        vat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        vat.setText("VAT :             Rs.");

        grandTotal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        grandTotal.setText("Grand Total : Rs.");

        doneButton.setForeground(new java.awt.Color(255, 255, 255));
        doneButton.setText("Done");
        doneButton.setBorderColor(new java.awt.Color(13, 180, 185));
        doneButton.setBorderPainted(false);
        doneButton.setColor(new java.awt.Color(13, 180, 185));
        doneButton.setColorClick(new java.awt.Color(11, 140, 144));
        doneButton.setColorOver(new java.awt.Color(11, 140, 144));
        doneButton.setFocusPainted(false);
        doneButton.setFocusable(false);
        doneButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        doneButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        doneButton.setIconTextGap(30);
        doneButton.setRadius(20);
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(grnID, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(discount)
                            .addComponent(subTotal))
                        .addGap(217, 217, 217)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vat)
                            .addComponent(grandTotal))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grnID)
                    .addComponent(date))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vat)
                        .addGap(18, 18, 18)
                        .addComponent(grandTotal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(subTotal)
                        .addGap(18, 18, 18)
                        .addComponent(discount)))
                .addGap(7, 7, 7)
                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_doneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowGRNDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowGRNDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowGRNDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowGRNDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowGRNDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GRNTable;
    private javax.swing.JLabel date;
    private javax.swing.JLabel discount;
    private button.MyButton doneButton;
    private javax.swing.JLabel grandTotal;
    private javax.swing.JLabel grnID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel subTotal;
    private javax.swing.JLabel vat;
    // End of variables declaration//GEN-END:variables
}
