/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Reports;

import DBConnect.DBconnect;
import Dashboard.Dashboard;
import Manage.Manage;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Umindu
 */
public class Reports extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reports
     */
    CardLayout cardLayout;

    JDesktopPane mainWindowPanel;
    Dashboard dashboard;

    public Reports() {
        initComponents();

        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);

        cardLayout = (CardLayout) panelCards.getLayout();

        LoadEnterdVehiclesTable("All");

        DepSerEditButton.setVisible(false);
        DepSerCancelButton.setVisible(false);

        EntSerEditButton.setVisible(false);
        EntSerCancelButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        showEnterdVehiclePaneButton = new button.MyButton();
        showDepartedVehiclePaneButton = new button.MyButton();
        VehicleTypesButton = new button.MyButton();
        panelCards = new javax.swing.JPanel();
        enterdVehiclesCard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterdVehiclesTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        EntSerEditButton = new button.MyButton();
        EntSerCancelButton = new button.MyButton();
        searchEntVehicle = new fosalgo.FTextField();
        departedVehiclesCard = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        departedVehiclesTable = new javax.swing.JTable();
        DepSerCancelButton = new button.MyButton();
        DepSerEditButton = new button.MyButton();
        searchDepVehicle = new fosalgo.FTextField();
        dailyReport = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        showEnterdVehiclePaneButton1 = new button.MyButton();
        showDepartedVehiclePaneButton1 = new button.MyButton();
        VehicleTypesButton1 = new button.MyButton();
        panelCards1 = new javax.swing.JPanel();
        enterdVehiclesCard1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        enterdVehiclesTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        EntSerEditButton1 = new button.MyButton();
        EntSerCancelButton1 = new button.MyButton();
        searchEntVehicle1 = new fosalgo.FTextField();
        departedVehiclesCard1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        departedVehiclesTable1 = new javax.swing.JTable();
        DepSerCancelButton1 = new button.MyButton();
        DepSerEditButton1 = new button.MyButton();
        searchDepVehicle1 = new fosalgo.FTextField();
        dailyReport1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBorder(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 10));

        showEnterdVehiclePaneButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        showEnterdVehiclePaneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/angle-small-down.png"))); // NOI18N
        showEnterdVehiclePaneButton.setText("Enterd Vehicles");
        showEnterdVehiclePaneButton.setBorderColor(new java.awt.Color(255, 255, 255));
        showEnterdVehiclePaneButton.setBorderPainted(false);
        showEnterdVehiclePaneButton.setColorClick(new java.awt.Color(126, 240, 244));
        showEnterdVehiclePaneButton.setColorOver(new java.awt.Color(126, 240, 244));
        showEnterdVehiclePaneButton.setFocusPainted(false);
        showEnterdVehiclePaneButton.setFocusable(false);
        showEnterdVehiclePaneButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showEnterdVehiclePaneButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showEnterdVehiclePaneButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        showEnterdVehiclePaneButton.setIconTextGap(10);
        showEnterdVehiclePaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEnterdVehiclePaneButtonActionPerformed(evt);
            }
        });

        showDepartedVehiclePaneButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        showDepartedVehiclePaneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/angle-small-down.png"))); // NOI18N
        showDepartedVehiclePaneButton.setText("Departed Vehicles");
        showDepartedVehiclePaneButton.setBorderColor(new java.awt.Color(255, 255, 255));
        showDepartedVehiclePaneButton.setBorderPainted(false);
        showDepartedVehiclePaneButton.setColorClick(new java.awt.Color(126, 240, 244));
        showDepartedVehiclePaneButton.setColorOver(new java.awt.Color(126, 240, 244));
        showDepartedVehiclePaneButton.setFocusPainted(false);
        showDepartedVehiclePaneButton.setFocusable(false);
        showDepartedVehiclePaneButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showDepartedVehiclePaneButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showDepartedVehiclePaneButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        showDepartedVehiclePaneButton.setIconTextGap(10);
        showDepartedVehiclePaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDepartedVehiclePaneButtonActionPerformed(evt);
            }
        });

        VehicleTypesButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        VehicleTypesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/angle-small-down.png"))); // NOI18N
        VehicleTypesButton.setText("Daily Report");
        VehicleTypesButton.setBorderColor(new java.awt.Color(255, 255, 255));
        VehicleTypesButton.setBorderPainted(false);
        VehicleTypesButton.setColorClick(new java.awt.Color(126, 240, 244));
        VehicleTypesButton.setColorOver(new java.awt.Color(126, 240, 244));
        VehicleTypesButton.setFocusPainted(false);
        VehicleTypesButton.setFocusable(false);
        VehicleTypesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VehicleTypesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        VehicleTypesButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        VehicleTypesButton.setIconTextGap(10);
        VehicleTypesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleTypesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showEnterdVehiclePaneButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(showDepartedVehiclePaneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(VehicleTypesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(showEnterdVehiclePaneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(showDepartedVehiclePaneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(VehicleTypesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelCards.setBackground(new java.awt.Color(255, 255, 255));
        panelCards.setLayout(new java.awt.CardLayout());

        enterdVehiclesCard.setBackground(new java.awt.Color(255, 255, 255));
        enterdVehiclesCard.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        enterdVehiclesTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enterdVehiclesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        enterdVehiclesTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterdVehiclesTable.setGridColor(new java.awt.Color(204, 204, 204));
        enterdVehiclesTable.setName(""); // NOI18N
        enterdVehiclesTable.setRowHeight(25);
        enterdVehiclesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterdVehiclesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(enterdVehiclesTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Enterd Vehicles List");

        EntSerEditButton.setText("Service Edit");
        EntSerEditButton.setBorderColor(new java.awt.Color(13, 180, 185));
        EntSerEditButton.setBorderPainted(false);
        EntSerEditButton.setColorClick(new java.awt.Color(184, 248, 250));
        EntSerEditButton.setColorOver(new java.awt.Color(184, 248, 250));
        EntSerEditButton.setFocusPainted(false);
        EntSerEditButton.setFocusable(false);
        EntSerEditButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EntSerEditButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        EntSerEditButton.setRadius(20);
        EntSerEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntSerEditButtonActionPerformed(evt);
            }
        });

        EntSerCancelButton.setText("Service Cancel");
        EntSerCancelButton.setBorderColor(new java.awt.Color(13, 180, 185));
        EntSerCancelButton.setBorderPainted(false);
        EntSerCancelButton.setColorClick(new java.awt.Color(184, 248, 250));
        EntSerCancelButton.setColorOver(new java.awt.Color(184, 248, 250));
        EntSerCancelButton.setFocusPainted(false);
        EntSerCancelButton.setFocusable(false);
        EntSerCancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EntSerCancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        EntSerCancelButton.setRadius(20);
        EntSerCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntSerCancelButtonActionPerformed(evt);
            }
        });

        searchEntVehicle.setForeground(new java.awt.Color(153, 153, 153));
        searchEntVehicle.setText("Search by invoice no or vehicle no");
        searchEntVehicle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchEntVehicle.setRadius(20);
        searchEntVehicle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchEntVehicleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchEntVehicleFocusLost(evt);
            }
        });
        searchEntVehicle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchEntVehicleKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout enterdVehiclesCardLayout = new javax.swing.GroupLayout(enterdVehiclesCard);
        enterdVehiclesCard.setLayout(enterdVehiclesCardLayout);
        enterdVehiclesCardLayout.setHorizontalGroup(
            enterdVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterdVehiclesCardLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(searchEntVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EntSerEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EntSerCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        enterdVehiclesCardLayout.setVerticalGroup(
            enterdVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterdVehiclesCardLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(enterdVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntSerCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntSerEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchEntVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
        );

        panelCards.add(enterdVehiclesCard, "enterdVehiclesCard");

        departedVehiclesCard.setBackground(new java.awt.Color(255, 255, 255));
        departedVehiclesCard.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Departed Vehicles List");

        departedVehiclesTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        departedVehiclesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        departedVehiclesTable.setGridColor(new java.awt.Color(204, 204, 204));
        departedVehiclesTable.setRowHeight(25);
        departedVehiclesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departedVehiclesTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(departedVehiclesTable);

        DepSerCancelButton.setText("Service Cancel");
        DepSerCancelButton.setBorderColor(new java.awt.Color(13, 180, 185));
        DepSerCancelButton.setBorderPainted(false);
        DepSerCancelButton.setColorClick(new java.awt.Color(184, 248, 250));
        DepSerCancelButton.setColorOver(new java.awt.Color(184, 248, 250));
        DepSerCancelButton.setFocusPainted(false);
        DepSerCancelButton.setFocusable(false);
        DepSerCancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DepSerCancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        DepSerCancelButton.setRadius(20);
        DepSerCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepSerCancelButtonActionPerformed(evt);
            }
        });

        DepSerEditButton.setText("Service Edit");
        DepSerEditButton.setBorderColor(new java.awt.Color(13, 180, 185));
        DepSerEditButton.setBorderPainted(false);
        DepSerEditButton.setColorClick(new java.awt.Color(184, 248, 250));
        DepSerEditButton.setColorOver(new java.awt.Color(184, 248, 250));
        DepSerEditButton.setFocusPainted(false);
        DepSerEditButton.setFocusable(false);
        DepSerEditButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DepSerEditButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        DepSerEditButton.setRadius(20);
        DepSerEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepSerEditButtonActionPerformed(evt);
            }
        });

        searchDepVehicle.setForeground(new java.awt.Color(153, 153, 153));
        searchDepVehicle.setText("Search by invoice no or vehicle no");
        searchDepVehicle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchDepVehicle.setRadius(20);
        searchDepVehicle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchDepVehicleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchDepVehicleFocusLost(evt);
            }
        });
        searchDepVehicle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchDepVehicleKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout departedVehiclesCardLayout = new javax.swing.GroupLayout(departedVehiclesCard);
        departedVehiclesCard.setLayout(departedVehiclesCardLayout);
        departedVehiclesCardLayout.setHorizontalGroup(
            departedVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departedVehiclesCardLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(departedVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(departedVehiclesCardLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                        .addComponent(searchDepVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DepSerEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DepSerCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        departedVehiclesCardLayout.setVerticalGroup(
            departedVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departedVehiclesCardLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(departedVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepSerCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepSerEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(searchDepVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        panelCards.add(departedVehiclesCard, "departedVehiclesCard");

        dailyReport.setBackground(new java.awt.Color(255, 255, 255));
        dailyReport.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Opening  Drawer Amount ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Rs. 0.00");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Other Payment Sale");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Rs. 0.00");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(10, 10, 10))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Cash Payment Sale");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Rs. 0.00");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(10, 10, 10))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout dailyReportLayout = new javax.swing.GroupLayout(dailyReport);
        dailyReport.setLayout(dailyReportLayout);
        dailyReportLayout.setHorizontalGroup(
            dailyReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dailyReportLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dailyReportLayout.setVerticalGroup(
            dailyReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dailyReportLayout.createSequentialGroup()
                .addGroup(dailyReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 426, Short.MAX_VALUE))
        );

        panelCards.add(dailyReport, "dailyReport");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jInternalFrame1.setBorder(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 10));

        showEnterdVehiclePaneButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        showEnterdVehiclePaneButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/angle-small-down.png"))); // NOI18N
        showEnterdVehiclePaneButton1.setText("Enterd Vehicles");
        showEnterdVehiclePaneButton1.setBorderColor(new java.awt.Color(255, 255, 255));
        showEnterdVehiclePaneButton1.setBorderPainted(false);
        showEnterdVehiclePaneButton1.setColorClick(new java.awt.Color(126, 240, 244));
        showEnterdVehiclePaneButton1.setColorOver(new java.awt.Color(126, 240, 244));
        showEnterdVehiclePaneButton1.setFocusPainted(false);
        showEnterdVehiclePaneButton1.setFocusable(false);
        showEnterdVehiclePaneButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showEnterdVehiclePaneButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showEnterdVehiclePaneButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        showEnterdVehiclePaneButton1.setIconTextGap(10);
        showEnterdVehiclePaneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEnterdVehiclePaneButton1ActionPerformed(evt);
            }
        });

        showDepartedVehiclePaneButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        showDepartedVehiclePaneButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/angle-small-down.png"))); // NOI18N
        showDepartedVehiclePaneButton1.setText("Departed Vehicles");
        showDepartedVehiclePaneButton1.setBorderColor(new java.awt.Color(255, 255, 255));
        showDepartedVehiclePaneButton1.setBorderPainted(false);
        showDepartedVehiclePaneButton1.setColorClick(new java.awt.Color(126, 240, 244));
        showDepartedVehiclePaneButton1.setColorOver(new java.awt.Color(126, 240, 244));
        showDepartedVehiclePaneButton1.setFocusPainted(false);
        showDepartedVehiclePaneButton1.setFocusable(false);
        showDepartedVehiclePaneButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showDepartedVehiclePaneButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showDepartedVehiclePaneButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        showDepartedVehiclePaneButton1.setIconTextGap(10);
        showDepartedVehiclePaneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDepartedVehiclePaneButton1ActionPerformed(evt);
            }
        });

        VehicleTypesButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        VehicleTypesButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/angle-small-down.png"))); // NOI18N
        VehicleTypesButton1.setText("Daily Report");
        VehicleTypesButton1.setBorderColor(new java.awt.Color(255, 255, 255));
        VehicleTypesButton1.setBorderPainted(false);
        VehicleTypesButton1.setColorClick(new java.awt.Color(126, 240, 244));
        VehicleTypesButton1.setColorOver(new java.awt.Color(126, 240, 244));
        VehicleTypesButton1.setFocusPainted(false);
        VehicleTypesButton1.setFocusable(false);
        VehicleTypesButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VehicleTypesButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        VehicleTypesButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        VehicleTypesButton1.setIconTextGap(10);
        VehicleTypesButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleTypesButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showEnterdVehiclePaneButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(showDepartedVehiclePaneButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(VehicleTypesButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(showEnterdVehiclePaneButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(showDepartedVehiclePaneButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(VehicleTypesButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelCards1.setBackground(new java.awt.Color(255, 255, 255));
        panelCards1.setLayout(new java.awt.CardLayout());

        enterdVehiclesCard1.setBackground(new java.awt.Color(255, 255, 255));
        enterdVehiclesCard1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        enterdVehiclesTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enterdVehiclesTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        enterdVehiclesTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterdVehiclesTable1.setGridColor(new java.awt.Color(204, 204, 204));
        enterdVehiclesTable1.setName(""); // NOI18N
        enterdVehiclesTable1.setRowHeight(25);
        enterdVehiclesTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterdVehiclesTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(enterdVehiclesTable1);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Enterd Vehicles List");

        EntSerEditButton1.setText("Service Edit");
        EntSerEditButton1.setBorderColor(new java.awt.Color(13, 180, 185));
        EntSerEditButton1.setBorderPainted(false);
        EntSerEditButton1.setColorClick(new java.awt.Color(184, 248, 250));
        EntSerEditButton1.setColorOver(new java.awt.Color(184, 248, 250));
        EntSerEditButton1.setFocusPainted(false);
        EntSerEditButton1.setFocusable(false);
        EntSerEditButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EntSerEditButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        EntSerEditButton1.setRadius(20);
        EntSerEditButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntSerEditButton1ActionPerformed(evt);
            }
        });

        EntSerCancelButton1.setText("Service Cancel");
        EntSerCancelButton1.setBorderColor(new java.awt.Color(13, 180, 185));
        EntSerCancelButton1.setBorderPainted(false);
        EntSerCancelButton1.setColorClick(new java.awt.Color(184, 248, 250));
        EntSerCancelButton1.setColorOver(new java.awt.Color(184, 248, 250));
        EntSerCancelButton1.setFocusPainted(false);
        EntSerCancelButton1.setFocusable(false);
        EntSerCancelButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EntSerCancelButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        EntSerCancelButton1.setRadius(20);
        EntSerCancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntSerCancelButton1ActionPerformed(evt);
            }
        });

        searchEntVehicle1.setForeground(new java.awt.Color(153, 153, 153));
        searchEntVehicle1.setText("Search by invoice no or vehicle no");
        searchEntVehicle1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchEntVehicle1.setRadius(20);
        searchEntVehicle1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchEntVehicle1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchEntVehicle1FocusLost(evt);
            }
        });
        searchEntVehicle1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchEntVehicle1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout enterdVehiclesCard1Layout = new javax.swing.GroupLayout(enterdVehiclesCard1);
        enterdVehiclesCard1.setLayout(enterdVehiclesCard1Layout);
        enterdVehiclesCard1Layout.setHorizontalGroup(
            enterdVehiclesCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterdVehiclesCard1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchEntVehicle1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EntSerEditButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EntSerCancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        enterdVehiclesCard1Layout.setVerticalGroup(
            enterdVehiclesCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterdVehiclesCard1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(enterdVehiclesCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntSerCancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntSerEditButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchEntVehicle1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
        );

        panelCards1.add(enterdVehiclesCard1, "enterdVehiclesCard");

        departedVehiclesCard1.setBackground(new java.awt.Color(255, 255, 255));
        departedVehiclesCard1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Departed Vehicles List");

        departedVehiclesTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        departedVehiclesTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        departedVehiclesTable1.setGridColor(new java.awt.Color(204, 204, 204));
        departedVehiclesTable1.setRowHeight(25);
        departedVehiclesTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departedVehiclesTable1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(departedVehiclesTable1);

        DepSerCancelButton1.setText("Service Cancel");
        DepSerCancelButton1.setBorderColor(new java.awt.Color(13, 180, 185));
        DepSerCancelButton1.setBorderPainted(false);
        DepSerCancelButton1.setColorClick(new java.awt.Color(184, 248, 250));
        DepSerCancelButton1.setColorOver(new java.awt.Color(184, 248, 250));
        DepSerCancelButton1.setFocusPainted(false);
        DepSerCancelButton1.setFocusable(false);
        DepSerCancelButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DepSerCancelButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        DepSerCancelButton1.setRadius(20);
        DepSerCancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepSerCancelButton1ActionPerformed(evt);
            }
        });

        DepSerEditButton1.setText("Service Edit");
        DepSerEditButton1.setBorderColor(new java.awt.Color(13, 180, 185));
        DepSerEditButton1.setBorderPainted(false);
        DepSerEditButton1.setColorClick(new java.awt.Color(184, 248, 250));
        DepSerEditButton1.setColorOver(new java.awt.Color(184, 248, 250));
        DepSerEditButton1.setFocusPainted(false);
        DepSerEditButton1.setFocusable(false);
        DepSerEditButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DepSerEditButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        DepSerEditButton1.setRadius(20);
        DepSerEditButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepSerEditButton1ActionPerformed(evt);
            }
        });

        searchDepVehicle1.setForeground(new java.awt.Color(153, 153, 153));
        searchDepVehicle1.setText("Search by invoice no or vehicle no");
        searchDepVehicle1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchDepVehicle1.setRadius(20);
        searchDepVehicle1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchDepVehicle1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchDepVehicle1FocusLost(evt);
            }
        });
        searchDepVehicle1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchDepVehicle1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout departedVehiclesCard1Layout = new javax.swing.GroupLayout(departedVehiclesCard1);
        departedVehiclesCard1.setLayout(departedVehiclesCard1Layout);
        departedVehiclesCard1Layout.setHorizontalGroup(
            departedVehiclesCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departedVehiclesCard1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(departedVehiclesCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(departedVehiclesCard1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchDepVehicle1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DepSerEditButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DepSerCancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        departedVehiclesCard1Layout.setVerticalGroup(
            departedVehiclesCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departedVehiclesCard1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(departedVehiclesCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepSerCancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepSerEditButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(searchDepVehicle1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        panelCards1.add(departedVehiclesCard1, "departedVehiclesCard");

        dailyReport1.setBackground(new java.awt.Color(255, 255, 255));
        dailyReport1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Opening  Drawer Amount ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Rs. 0.00");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel12))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Other Payment Sale");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText("Rs. 0.00");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(10, 10, 10))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Cash Payment Sale");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("Rs. 0.00");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(10, 10, 10))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout dailyReport1Layout = new javax.swing.GroupLayout(dailyReport1);
        dailyReport1.setLayout(dailyReport1Layout);
        dailyReport1Layout.setHorizontalGroup(
            dailyReport1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dailyReport1Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dailyReport1Layout.setVerticalGroup(
            dailyReport1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dailyReport1Layout.createSequentialGroup()
                .addGroup(dailyReport1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelCards1.add(dailyReport1, "dailyReport");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCards1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCards1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 599, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 600, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 312, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 312, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setObject(JDesktopPane mainWindowPanel, Dashboard dashboard) {
        this.mainWindowPanel = mainWindowPanel;
        this.dashboard = dashboard;
    }

    private void showEnterdVehiclePaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEnterdVehiclePaneButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelCards, "enterdVehiclesCard");

        LoadEnterdVehiclesTable("All");
    }//GEN-LAST:event_showEnterdVehiclePaneButtonActionPerformed

    private void showDepartedVehiclePaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDepartedVehiclePaneButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelCards, "departedVehiclesCard");

        LoadDepartedVehiclesTable("All");
    }//GEN-LAST:event_showDepartedVehiclePaneButtonActionPerformed

    private void DepSerCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepSerCancelButtonActionPerformed
        // TODO add your handling code here:
        int invoiceID = (int) departedVehiclesTable.getModel().getValueAt(departedVehiclesTable.getSelectedRow(), 0);
        CancelService(invoiceID);
    }//GEN-LAST:event_DepSerCancelButtonActionPerformed

    private void DepSerEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepSerEditButtonActionPerformed
        // TODO add your handling code here:
        int invoiceID = (int) departedVehiclesTable.getModel().getValueAt(departedVehiclesTable.getSelectedRow(), 0);
//        CancelService(invoiceID, "Dep", null);
        dashboard.EditServiceAndProduct(invoiceID);
    }//GEN-LAST:event_DepSerEditButtonActionPerformed

    private void departedVehiclesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departedVehiclesTableMouseClicked
        // TODO add your handling code here:
        DepSerEditButton.setVisible(true);
        DepSerCancelButton.setVisible(true);
    }//GEN-LAST:event_departedVehiclesTableMouseClicked

    private void EntSerEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntSerEditButtonActionPerformed
        // TODO add your handling code here:
        int invoiceID = (int) enterdVehiclesTable.getModel().getValueAt(enterdVehiclesTable.getSelectedRow(), 0);
//        CancelService(invoiceID, "Ent", null);
        dashboard.EditServiceAndProduct(invoiceID);


    }//GEN-LAST:event_EntSerEditButtonActionPerformed

    private void EntSerCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntSerCancelButtonActionPerformed
        // TODO add your handling code here:
        int invoiceID = (int) enterdVehiclesTable.getModel().getValueAt(enterdVehiclesTable.getSelectedRow(), 0);
        CancelService(invoiceID);
    }//GEN-LAST:event_EntSerCancelButtonActionPerformed

    private void enterdVehiclesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterdVehiclesTableMouseClicked
        // TODO add your handling code here:
        EntSerEditButton.setVisible(true);
        EntSerCancelButton.setVisible(true);
    }//GEN-LAST:event_enterdVehiclesTableMouseClicked

    private void searchDepVehicleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchDepVehicleFocusLost
        // TODO add your handling code here:
        if (searchDepVehicle.getText().equals("")) {
            searchDepVehicle.setText("Search by invoice no or vehicle no");
            searchDepVehicle.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_searchDepVehicleFocusLost

    private void searchDepVehicleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchDepVehicleFocusGained
        // TODO add your handling code here:
        if (searchDepVehicle.getText().equals("Search by invoice no or vehicle no")) {
            searchDepVehicle.setText("");
            searchDepVehicle.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchDepVehicleFocusGained

    private void searchEntVehicleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchEntVehicleFocusGained
        // TODO add your handling code here:
        if (searchEntVehicle.getText().equals("Search by invoice no or vehicle no")) {
            searchEntVehicle.setText("");
            searchEntVehicle.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchEntVehicleFocusGained

    private void searchEntVehicleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchEntVehicleFocusLost
        // TODO add your handling code here:
        if (searchEntVehicle.getText().equals("")) {
            searchEntVehicle.setText("Search by invoice no or vehicle no");
            searchEntVehicle.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_searchEntVehicleFocusLost

    private void searchEntVehicleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchEntVehicleKeyReleased
        // TODO add your handling code here:
        LoadEnterdVehiclesTable(searchEntVehicle.getText());
    }//GEN-LAST:event_searchEntVehicleKeyReleased

    private void searchDepVehicleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchDepVehicleKeyReleased
        // TODO add your handling code here:
        LoadDepartedVehiclesTable(searchDepVehicle.getText());
    }//GEN-LAST:event_searchDepVehicleKeyReleased

    private void VehicleTypesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleTypesButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelCards, "dailyReport");
    }//GEN-LAST:event_VehicleTypesButtonActionPerformed

    private void showEnterdVehiclePaneButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEnterdVehiclePaneButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showEnterdVehiclePaneButton1ActionPerformed

    private void showDepartedVehiclePaneButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDepartedVehiclePaneButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showDepartedVehiclePaneButton1ActionPerformed

    private void VehicleTypesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleTypesButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleTypesButton1ActionPerformed

    private void enterdVehiclesTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterdVehiclesTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_enterdVehiclesTable1MouseClicked

    private void EntSerEditButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntSerEditButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntSerEditButton1ActionPerformed

    private void EntSerCancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntSerCancelButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntSerCancelButton1ActionPerformed

    private void searchEntVehicle1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchEntVehicle1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_searchEntVehicle1FocusGained

    private void searchEntVehicle1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchEntVehicle1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_searchEntVehicle1FocusLost

    private void searchEntVehicle1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchEntVehicle1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchEntVehicle1KeyReleased

    private void departedVehiclesTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departedVehiclesTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_departedVehiclesTable1MouseClicked

    private void DepSerCancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepSerCancelButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepSerCancelButton1ActionPerformed

    private void DepSerEditButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepSerEditButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepSerEditButton1ActionPerformed

    private void searchDepVehicle1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchDepVehicle1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_searchDepVehicle1FocusGained

    private void searchDepVehicle1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchDepVehicle1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_searchDepVehicle1FocusLost

    private void searchDepVehicle1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchDepVehicle1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchDepVehicle1KeyReleased

    public void LoadEnterdVehiclesTable(String search) {
        //serviceUnitTable data load
        JTableHeader header = enterdVehiclesTable.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 14));
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            if (search.equals("All")) {
                statement.execute("Select InvoiceNo, Date, VehicleNo, OwnerName, Phone, VehicleType, Description From VehicleDetails Where States = 'Processing'");
            } else {
                statement.execute("Select InvoiceNo, Date, VehicleNo, OwnerName, Phone, VehicleType, Description From VehicleDetails Where (InvoiceNo like '%" + search + "%' OR VehicleNo like '%" + search + "%') AND States = 'Processing'");
            }

            ResultSet resultSet = statement.getResultSet();

            enterdVehiclesTable.setModel(DbUtils.resultSetToTableModel(resultSet));

        } catch (SQLException ex) {
            Logger.getLogger(Manage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void LoadDepartedVehiclesTable(String search) {
        //serviceUnitTable data load
        JTableHeader header = departedVehiclesTable.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 14));
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            if (search.equals("All")) {
                statement.execute("Select InvoiceNo, Date, VehicleNo, OwnerName, Phone, VehicleType, Description From VehicleDetails Where States = 'Done'");
            } else {
                statement.execute("Select InvoiceNo, Date, VehicleNo, OwnerName, Phone, VehicleType, Description From VehicleDetails Where (InvoiceNo like '%" + search + "%' OR VehicleNo like '%" + search + "%') AND States = 'Done'");
            }
            ResultSet resultSet = statement.getResultSet();

            departedVehiclesTable.setModel(DbUtils.resultSetToTableModel(resultSet));

        } catch (SQLException ex) {
            Logger.getLogger(Manage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void CancelService(int invoiceID) {
        CancelService editAndCancelService = new CancelService(invoiceID);
        editAndCancelService.setObject(this);
        editAndCancelService.setLocationRelativeTo(null);
        editAndCancelService.setExtendedState(JFrame.MAXIMIZED_BOTH);
        editAndCancelService.setBackground(new Color(0, 0, 0, 150));
        editAndCancelService.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.MyButton DepSerCancelButton;
    private button.MyButton DepSerCancelButton1;
    private button.MyButton DepSerEditButton;
    private button.MyButton DepSerEditButton1;
    private button.MyButton EntSerCancelButton;
    private button.MyButton EntSerCancelButton1;
    private button.MyButton EntSerEditButton;
    private button.MyButton EntSerEditButton1;
    private button.MyButton VehicleTypesButton;
    private button.MyButton VehicleTypesButton1;
    private javax.swing.JPanel dailyReport;
    private javax.swing.JPanel dailyReport1;
    private javax.swing.JPanel departedVehiclesCard;
    private javax.swing.JPanel departedVehiclesCard1;
    private javax.swing.JTable departedVehiclesTable;
    private javax.swing.JTable departedVehiclesTable1;
    private javax.swing.JPanel enterdVehiclesCard;
    private javax.swing.JPanel enterdVehiclesCard1;
    private javax.swing.JTable enterdVehiclesTable;
    private javax.swing.JTable enterdVehiclesTable1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panelCards;
    private javax.swing.JPanel panelCards1;
    private fosalgo.FTextField searchDepVehicle;
    private fosalgo.FTextField searchDepVehicle1;
    private fosalgo.FTextField searchEntVehicle;
    private fosalgo.FTextField searchEntVehicle1;
    private button.MyButton showDepartedVehiclePaneButton;
    private button.MyButton showDepartedVehiclePaneButton1;
    private button.MyButton showEnterdVehiclePaneButton;
    private button.MyButton showEnterdVehiclePaneButton1;
    // End of variables declaration//GEN-END:variables
}
