/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Reports;

import DBConnect.DBconnect;
import Dashboard.Dashboard;
import Manage.Manage;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Umindu
 */
public class Reports extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reports
     */
    CardLayout cardLayout;

    JDesktopPane mainWindowPanel;
    Dashboard dashboard;

    public Reports() {
        initComponents();

        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);

        cardLayout = (CardLayout) panelCards.getLayout();

        LoadEnterdVehiclesTable("All");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        showEnterdVehiclePaneButton = new button.MyButton();
        showDepartedVehiclePaneButton = new button.MyButton();
        dailyReportButton = new button.MyButton();
        salesReportButton = new button.MyButton();
        stockReportButton = new button.MyButton();
        panelCards = new javax.swing.JPanel();
        enterdVehiclesCard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterdVehiclesTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        searchEntVehicle = new fosalgo.FTextField();
        departedVehiclesCard = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        departedVehiclesTable = new javax.swing.JTable();
        searchDepVehicle = new fosalgo.FTextField();
        dailyReport = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        openDrawerAmount = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        otherPayments = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cashPayments = new javax.swing.JLabel();
        searchDailySalesReport = new fosalgo.FTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        dailySalesReportTable = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        salesReport = new javax.swing.JPanel();
        searchSalesReport = new fosalgo.FTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        salesReportTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        stockReport = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        searchStock = new fosalgo.FTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        stockTable = new javax.swing.JTable();

        setBorder(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 10));

        showEnterdVehiclePaneButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        showEnterdVehiclePaneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/angle-small-down.png"))); // NOI18N
        showEnterdVehiclePaneButton.setText("Enterd Vehicles");
        showEnterdVehiclePaneButton.setBorderColor(new java.awt.Color(255, 255, 255));
        showEnterdVehiclePaneButton.setBorderPainted(false);
        showEnterdVehiclePaneButton.setColorClick(new java.awt.Color(126, 240, 244));
        showEnterdVehiclePaneButton.setColorOver(new java.awt.Color(126, 240, 244));
        showEnterdVehiclePaneButton.setFocusPainted(false);
        showEnterdVehiclePaneButton.setFocusable(false);
        showEnterdVehiclePaneButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showEnterdVehiclePaneButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showEnterdVehiclePaneButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        showEnterdVehiclePaneButton.setIconTextGap(10);
        showEnterdVehiclePaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEnterdVehiclePaneButtonActionPerformed(evt);
            }
        });

        showDepartedVehiclePaneButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        showDepartedVehiclePaneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/angle-small-down.png"))); // NOI18N
        showDepartedVehiclePaneButton.setText("Departed Vehicles");
        showDepartedVehiclePaneButton.setBorderColor(new java.awt.Color(255, 255, 255));
        showDepartedVehiclePaneButton.setBorderPainted(false);
        showDepartedVehiclePaneButton.setColorClick(new java.awt.Color(126, 240, 244));
        showDepartedVehiclePaneButton.setColorOver(new java.awt.Color(126, 240, 244));
        showDepartedVehiclePaneButton.setFocusPainted(false);
        showDepartedVehiclePaneButton.setFocusable(false);
        showDepartedVehiclePaneButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showDepartedVehiclePaneButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showDepartedVehiclePaneButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        showDepartedVehiclePaneButton.setIconTextGap(10);
        showDepartedVehiclePaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDepartedVehiclePaneButtonActionPerformed(evt);
            }
        });

        dailyReportButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        dailyReportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/angle-small-down.png"))); // NOI18N
        dailyReportButton.setText("Daily Report");
        dailyReportButton.setBorderColor(new java.awt.Color(255, 255, 255));
        dailyReportButton.setBorderPainted(false);
        dailyReportButton.setColorClick(new java.awt.Color(126, 240, 244));
        dailyReportButton.setColorOver(new java.awt.Color(126, 240, 244));
        dailyReportButton.setFocusPainted(false);
        dailyReportButton.setFocusable(false);
        dailyReportButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dailyReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dailyReportButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        dailyReportButton.setIconTextGap(10);
        dailyReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyReportButtonActionPerformed(evt);
            }
        });

        salesReportButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        salesReportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/angle-small-down.png"))); // NOI18N
        salesReportButton.setText("Sales Report");
        salesReportButton.setBorderColor(new java.awt.Color(255, 255, 255));
        salesReportButton.setBorderPainted(false);
        salesReportButton.setColorClick(new java.awt.Color(126, 240, 244));
        salesReportButton.setColorOver(new java.awt.Color(126, 240, 244));
        salesReportButton.setFocusPainted(false);
        salesReportButton.setFocusable(false);
        salesReportButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salesReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salesReportButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        salesReportButton.setIconTextGap(10);
        salesReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesReportButtonActionPerformed(evt);
            }
        });

        stockReportButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        stockReportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/angle-small-down.png"))); // NOI18N
        stockReportButton.setText("Stock Report");
        stockReportButton.setBorderColor(new java.awt.Color(255, 255, 255));
        stockReportButton.setBorderPainted(false);
        stockReportButton.setColorClick(new java.awt.Color(126, 240, 244));
        stockReportButton.setColorOver(new java.awt.Color(126, 240, 244));
        stockReportButton.setFocusPainted(false);
        stockReportButton.setFocusable(false);
        stockReportButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stockReportButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stockReportButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        stockReportButton.setIconTextGap(10);
        stockReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showEnterdVehiclePaneButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(showDepartedVehiclePaneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dailyReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(salesReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stockReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(showEnterdVehiclePaneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(showDepartedVehiclePaneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dailyReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(salesReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(stockReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelCards.setBackground(new java.awt.Color(255, 255, 255));
        panelCards.setLayout(new java.awt.CardLayout());

        enterdVehiclesCard.setBackground(new java.awt.Color(255, 255, 255));
        enterdVehiclesCard.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        enterdVehiclesTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enterdVehiclesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        enterdVehiclesTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterdVehiclesTable.setGridColor(new java.awt.Color(204, 204, 204));
        enterdVehiclesTable.setName(""); // NOI18N
        enterdVehiclesTable.setRowHeight(25);
        enterdVehiclesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterdVehiclesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(enterdVehiclesTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Enterd Vehicles List");

        searchEntVehicle.setForeground(new java.awt.Color(153, 153, 153));
        searchEntVehicle.setText("Search by invoice no or vehicle no");
        searchEntVehicle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchEntVehicle.setRadius(20);
        searchEntVehicle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchEntVehicleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchEntVehicleFocusLost(evt);
            }
        });
        searchEntVehicle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchEntVehicleKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout enterdVehiclesCardLayout = new javax.swing.GroupLayout(enterdVehiclesCard);
        enterdVehiclesCard.setLayout(enterdVehiclesCardLayout);
        enterdVehiclesCardLayout.setHorizontalGroup(
            enterdVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterdVehiclesCardLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 542, Short.MAX_VALUE)
                .addComponent(searchEntVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        enterdVehiclesCardLayout.setVerticalGroup(
            enterdVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterdVehiclesCardLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(enterdVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchEntVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
        );

        panelCards.add(enterdVehiclesCard, "enterdVehiclesCard");

        departedVehiclesCard.setBackground(new java.awt.Color(255, 255, 255));
        departedVehiclesCard.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Departed Vehicles List");

        departedVehiclesTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        departedVehiclesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        departedVehiclesTable.setGridColor(new java.awt.Color(204, 204, 204));
        departedVehiclesTable.setRowHeight(25);
        departedVehiclesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departedVehiclesTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(departedVehiclesTable);

        searchDepVehicle.setForeground(new java.awt.Color(153, 153, 153));
        searchDepVehicle.setText("Search by invoice no or vehicle no");
        searchDepVehicle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchDepVehicle.setRadius(20);
        searchDepVehicle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchDepVehicleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchDepVehicleFocusLost(evt);
            }
        });
        searchDepVehicle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchDepVehicleKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout departedVehiclesCardLayout = new javax.swing.GroupLayout(departedVehiclesCard);
        departedVehiclesCard.setLayout(departedVehiclesCardLayout);
        departedVehiclesCardLayout.setHorizontalGroup(
            departedVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departedVehiclesCardLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(departedVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                    .addGroup(departedVehiclesCardLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchDepVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        departedVehiclesCardLayout.setVerticalGroup(
            departedVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departedVehiclesCardLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(departedVehiclesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(searchDepVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        panelCards.add(departedVehiclesCard, "departedVehiclesCard");

        dailyReport.setBackground(new java.awt.Color(255, 255, 255));
        dailyReport.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Opening  Drawer Amount ");

        openDrawerAmount.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        openDrawerAmount.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        openDrawerAmount.setText("Rs. 0.00");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(openDrawerAmount))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)))
                .addGap(10, 10, 10))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(openDrawerAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Other Payment Amount");

        otherPayments.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        otherPayments.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        otherPayments.setText("Rs. 0.00");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(otherPayments)
                .addGap(10, 10, 10))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(otherPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Cash Payment Amount");

        cashPayments.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cashPayments.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cashPayments.setText("Rs. 0.00");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cashPayments)
                .addGap(10, 10, 10))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cashPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        searchDailySalesReport.setForeground(new java.awt.Color(153, 153, 153));
        searchDailySalesReport.setText("Search by invoice no or vehicle no");
        searchDailySalesReport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchDailySalesReport.setRadius(20);
        searchDailySalesReport.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchDailySalesReportFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchDailySalesReportFocusLost(evt);
            }
        });
        searchDailySalesReport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchDailySalesReportKeyReleased(evt);
            }
        });

        dailySalesReportTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dailySalesReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dailySalesReportTable.setGridColor(new java.awt.Color(204, 204, 204));
        dailySalesReportTable.setRowHeight(25);
        dailySalesReportTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dailySalesReportTableMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(dailySalesReportTable);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Daily Sales List");

        javax.swing.GroupLayout dailyReportLayout = new javax.swing.GroupLayout(dailyReport);
        dailyReport.setLayout(dailyReportLayout);
        dailyReportLayout.setHorizontalGroup(
            dailyReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dailyReportLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
            .addGroup(dailyReportLayout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchDailySalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dailyReportLayout.setVerticalGroup(
            dailyReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dailyReportLayout.createSequentialGroup()
                .addGroup(dailyReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dailyReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(searchDailySalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
        );

        panelCards.add(dailyReport, "dailyReport");

        salesReport.setBackground(new java.awt.Color(255, 255, 255));
        salesReport.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        searchSalesReport.setForeground(new java.awt.Color(153, 153, 153));
        searchSalesReport.setText("Search by invoice no or vehicle no");
        searchSalesReport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchSalesReport.setRadius(20);
        searchSalesReport.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchSalesReportFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchSalesReportFocusLost(evt);
            }
        });
        searchSalesReport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchSalesReportKeyReleased(evt);
            }
        });

        salesReportTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salesReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        salesReportTable.setGridColor(new java.awt.Color(204, 204, 204));
        salesReportTable.setRowHeight(25);
        salesReportTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesReportTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(salesReportTable);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Sales List");

        javax.swing.GroupLayout salesReportLayout = new javax.swing.GroupLayout(salesReport);
        salesReport.setLayout(salesReportLayout);
        salesReportLayout.setHorizontalGroup(
            salesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesReportLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(salesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                    .addGroup(salesReportLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchSalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        salesReportLayout.setVerticalGroup(
            salesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesReportLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(salesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(searchSalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        panelCards.add(salesReport, "salesReport");

        stockReport.setBackground(new java.awt.Color(255, 255, 255));
        stockReport.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Stock");

        searchStock.setForeground(new java.awt.Color(153, 153, 153));
        searchStock.setText("Search by product ID or product name");
        searchStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchStock.setRadius(20);
        searchStock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchStockFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchStockFocusLost(evt);
            }
        });
        searchStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchStockKeyReleased(evt);
            }
        });

        stockTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        stockTable.setGridColor(new java.awt.Color(204, 204, 204));
        stockTable.setRowHeight(25);
        stockTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockTableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(stockTable);

        javax.swing.GroupLayout stockReportLayout = new javax.swing.GroupLayout(stockReport);
        stockReport.setLayout(stockReportLayout);
        stockReportLayout.setHorizontalGroup(
            stockReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockReportLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(stockReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                    .addGroup(stockReportLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        stockReportLayout.setVerticalGroup(
            stockReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockReportLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(stockReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(searchStock, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        panelCards.add(stockReport, "stockReport");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setObject(JDesktopPane mainWindowPanel, Dashboard dashboard) {
        this.mainWindowPanel = mainWindowPanel;
        this.dashboard = dashboard;
    }
    
    private void resetButtonStyle(){
        showEnterdVehiclePaneButton.setColor(Color.WHITE);
        showDepartedVehiclePaneButton.setColor(Color.WHITE);
        dailyReportButton.setColor(Color.WHITE);
        salesReportButton.setColor(Color.WHITE);
        stockReportButton.setColor(Color.WHITE);
    }

    private void showEnterdVehiclePaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEnterdVehiclePaneButtonActionPerformed
        resetButtonStyle();
        showEnterdVehiclePaneButton.setColor(new Color(184,248,250));
        
        cardLayout.show(panelCards, "enterdVehiclesCard");

        LoadEnterdVehiclesTable("All");
    }//GEN-LAST:event_showEnterdVehiclePaneButtonActionPerformed

    private void showDepartedVehiclePaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDepartedVehiclePaneButtonActionPerformed
        resetButtonStyle();
        showDepartedVehiclePaneButton.setColor(new Color(184,248,250));
        
        cardLayout.show(panelCards, "departedVehiclesCard");

        LoadDepartedVehiclesTable("All");
    }//GEN-LAST:event_showDepartedVehiclePaneButtonActionPerformed

    private void departedVehiclesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departedVehiclesTableMouseClicked
        int invoiceID = (int) departedVehiclesTable.getModel().getValueAt(departedVehiclesTable.getSelectedRow(), 0);
        
        ShowServiceDetails(invoiceID);
    }//GEN-LAST:event_departedVehiclesTableMouseClicked

    private void enterdVehiclesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterdVehiclesTableMouseClicked
        int invoiceID = (int) enterdVehiclesTable.getModel().getValueAt(enterdVehiclesTable.getSelectedRow(), 0);
        
        ShowEnteredVehicleDetails(invoiceID);
    }//GEN-LAST:event_enterdVehiclesTableMouseClicked

    private void searchDepVehicleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchDepVehicleFocusLost
        // TODO add your handling code here:
        if (searchDepVehicle.getText().equals("")) {
            searchDepVehicle.setText("Search by invoice no or vehicle no");
            searchDepVehicle.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_searchDepVehicleFocusLost

    private void searchDepVehicleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchDepVehicleFocusGained
        // TODO add your handling code here:
        if (searchDepVehicle.getText().equals("Search by invoice no or vehicle no")) {
            searchDepVehicle.setText("");
            searchDepVehicle.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchDepVehicleFocusGained

    private void searchEntVehicleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchEntVehicleFocusGained
        // TODO add your handling code here:
        if (searchEntVehicle.getText().equals("Search by invoice no or vehicle no")) {
            searchEntVehicle.setText("");
            searchEntVehicle.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchEntVehicleFocusGained

    private void searchEntVehicleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchEntVehicleFocusLost
        // TODO add your handling code here:
        if (searchEntVehicle.getText().equals("")) {
            searchEntVehicle.setText("Search by invoice no or vehicle no");
            searchEntVehicle.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_searchEntVehicleFocusLost

    private void searchEntVehicleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchEntVehicleKeyReleased
        // TODO add your handling code here:
        LoadEnterdVehiclesTable(searchEntVehicle.getText());
    }//GEN-LAST:event_searchEntVehicleKeyReleased

    private void searchDepVehicleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchDepVehicleKeyReleased
        // TODO add your handling code here:
        LoadDepartedVehiclesTable(searchDepVehicle.getText());
    }//GEN-LAST:event_searchDepVehicleKeyReleased

    private void dailyReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyReportButtonActionPerformed
        // TODO add your handling code here:
        resetButtonStyle();
        dailyReportButton.setColor(new Color(184,248,250));
        
        cardLayout.show(panelCards, "dailyReport");
        
        Date currentDate = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = dateFormat.format(currentDate);
        
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            statement.execute("SELECT OpeningDrawerAmount FROM DailySummary WHERE Date = '"+formattedDate+"'");
            ResultSet resultSet = statement.getResultSet();
            if(resultSet.next()){
                openDrawerAmount.setText("Rs. "+resultSet.getString("OpeningDrawerAmount"));
            }
            
            statement.execute("SELECT SUM(CashPayAmount) AS CashPaymentsAmount, SUM(CardPayAmount)+ SUM(QRPayAmount) AS OtherPaymentsAmount FROM PaymentDetails WHERE Date <= '"+formattedDate+" 23:59:59.000' AND Date > '"+formattedDate+" 00:00:00.000'");
            ResultSet resultSet2 = statement.getResultSet();
            if(resultSet2.next()){
                if(resultSet2.getString("CashPaymentsAmount") != null){
                    cashPayments.setText("Rs. "+resultSet2.getString("CashPaymentsAmount"));
                }else{
                    cashPayments.setText("Rs. 0.00");
                }
                if(resultSet2.getString("OtherPaymentsAmount") != null){
                    otherPayments.setText("Rs. "+resultSet2.getString("OtherPaymentsAmount"));
                }else{
                    otherPayments.setText("Rs. 0.00");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Manage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LoadDailySalesReportTable("All");
    }//GEN-LAST:event_dailyReportButtonActionPerformed

    private void salesReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesReportButtonActionPerformed
        resetButtonStyle();
        salesReportButton.setColor(new Color(184,248,250));
        
        cardLayout.show(panelCards, "salesReport");
        
        LoadSalesReportTable("All");
    }//GEN-LAST:event_salesReportButtonActionPerformed

    private void searchSalesReportFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchSalesReportFocusGained
        if (searchSalesReport.getText().equals("Search by invoice no or vehicle no")) {
            searchSalesReport.setText("");
            searchSalesReport.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchSalesReportFocusGained

    private void searchSalesReportFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchSalesReportFocusLost
        if (searchSalesReport.getText().equals("")) {
            searchSalesReport.setText("Search by invoice no or vehicle no");
            searchSalesReport.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_searchSalesReportFocusLost

    private void searchSalesReportKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchSalesReportKeyReleased
        // TODO add your handling code here:
        LoadSalesReportTable(searchSalesReport.getText());
    }//GEN-LAST:event_searchSalesReportKeyReleased

    private void salesReportTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesReportTableMouseClicked
        int invoiceID = (int) salesReportTable.getModel().getValueAt(salesReportTable.getSelectedRow(), 0);
        
        ShowServiceDetails(invoiceID);
    }//GEN-LAST:event_salesReportTableMouseClicked

    private void stockReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockReportButtonActionPerformed
        resetButtonStyle();
        stockReportButton.setColor(new Color(184,248,250));
        
        cardLayout.show(panelCards, "stockReport");
        
        LoadStockReportTable("All");
    }//GEN-LAST:event_stockReportButtonActionPerformed

    private void searchStockFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchStockFocusGained
        if (searchStock.getText().equals("Search by product ID or product name")) {
            searchStock.setText("");
            searchStock.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchStockFocusGained

    private void searchStockFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchStockFocusLost
        if (searchStock.getText().equals("")) {
            searchStock.setText("Search by product ID or product name");
            searchStock.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_searchStockFocusLost

    private void searchStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchStockKeyReleased
        LoadStockReportTable(searchStock.getText());
    }//GEN-LAST:event_searchStockKeyReleased

    private void stockTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stockTableMouseClicked

    private void searchDailySalesReportFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchDailySalesReportFocusGained
        if (searchDailySalesReport.getText().equals("Search by invoice no or vehicle no")) {
            searchDailySalesReport.setText("");
            searchDailySalesReport.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchDailySalesReportFocusGained

    private void searchDailySalesReportFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchDailySalesReportFocusLost
        if (searchDailySalesReport.getText().equals("")) {
            searchDailySalesReport.setText("Search by invoice no or vehicle no");
            searchDailySalesReport.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_searchDailySalesReportFocusLost

    private void searchDailySalesReportKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchDailySalesReportKeyReleased
        // TODO add your handling code here:d
        LoadDailySalesReportTable(searchDailySalesReport.getText());
    }//GEN-LAST:event_searchDailySalesReportKeyReleased

    private void dailySalesReportTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailySalesReportTableMouseClicked
        int invoiceID = (int) dailySalesReportTable.getModel().getValueAt(dailySalesReportTable.getSelectedRow(), 0);
        
        ShowServiceDetails(invoiceID);
    }//GEN-LAST:event_dailySalesReportTableMouseClicked

    public void LoadEnterdVehiclesTable(String search) {
        //serviceUnitTable data load
        JTableHeader header = enterdVehiclesTable.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 14));
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            if (search.equals("All")) {
                statement.execute("Select InvoiceNo, Date, VehicleNo, OwnerName, Phone, VehicleType, Description From VehicleDetails Where States = 'Processing'");
            } else {
                statement.execute("Select InvoiceNo, Date, VehicleNo, OwnerName, Phone, VehicleType, Description From VehicleDetails Where (InvoiceNo like '%" + search + "%' OR VehicleNo like '%" + search + "%') AND States = 'Processing'");
            }

            ResultSet resultSet = statement.getResultSet();

            enterdVehiclesTable.setModel(DbUtils.resultSetToTableModel(resultSet));

        } catch (SQLException ex) {
            Logger.getLogger(Manage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void LoadDepartedVehiclesTable(String search) {
        //serviceUnitTable data load
        JTableHeader header = departedVehiclesTable.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 14));
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            if (search.equals("All")) {
                statement.execute("Select InvoiceNo, Date, VehicleNo, OwnerName, Phone, VehicleType, Description From VehicleDetails Where States = 'Done'");
            } else {
                statement.execute("Select InvoiceNo, Date, VehicleNo, OwnerName, Phone, VehicleType, Description From VehicleDetails Where (InvoiceNo like '%" + search + "%' OR VehicleNo like '%" + search + "%') AND States = 'Done'");
            }
            ResultSet resultSet = statement.getResultSet();

            departedVehiclesTable.setModel(DbUtils.resultSetToTableModel(resultSet));

        } catch (SQLException ex) {
            Logger.getLogger(Manage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void LoadSalesReportTable(String search) {
        //salesReportTable data load
        JTableHeader header = salesReportTable.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 14));
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            if (search.equals("All")) {
                statement.execute("SELECT InvoiceID, VehicleDetails.VehicleNo, PaymentDetails.Date, PayableAmount, TotalPayAmount, Balance, Note FROM PaymentDetails INNER JOIN VehicleDetails ON PaymentDetails.InvoiceID = VehicleDetails.InvoiceNo");
            } else {
                statement.execute("SELECT InvoiceID, VehicleDetails.VehicleNo, PaymentDetails.Date, PayableAmount, TotalPayAmount, Balance, Note FROM PaymentDetails INNER JOIN VehicleDetails ON PaymentDetails.InvoiceID = VehicleDetails.InvoiceNo WHERE (PaymentDetails.InvoiceID like '%" + search + "%' OR VehicleDetails.VehicleNo like '%" + search + "%')");
            }
            ResultSet resultSet = statement.getResultSet();

            salesReportTable.setModel(DbUtils.resultSetToTableModel(resultSet));
        } catch (SQLException ex) {
            Logger.getLogger(Manage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void LoadDailySalesReportTable(String search) {
        Date currentDate = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = dateFormat.format(currentDate);
        
        JTableHeader header = dailySalesReportTable.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 14));
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            if (search.equals("All")) {
                statement.execute("SELECT InvoiceID, VehicleDetails.VehicleNo, PaymentDetails.Date, PayableAmount, TotalPayAmount, Balance, Note FROM PaymentDetails INNER JOIN VehicleDetails ON PaymentDetails.InvoiceID = VehicleDetails.InvoiceNo WHERE PaymentDetails.Date <= '"+formattedDate+" 23:59:59.000' AND PaymentDetails.Date > '"+formattedDate+" 00:00:00.000'");
            } else {
                statement.execute("SELECT InvoiceID, VehicleDetails.VehicleNo, PaymentDetails.Date, PayableAmount, TotalPayAmount, Balance, Note FROM PaymentDetails INNER JOIN VehicleDetails ON PaymentDetails.InvoiceID = VehicleDetails.InvoiceNo WHERE (PaymentDetails.InvoiceID like '%" + search + "%' OR VehicleDetails.VehicleNo like '%" + search + "%') AND (PaymentDetails.Date <= '"+formattedDate+" 23:59:59.000' AND PaymentDetails.Date > '"+formattedDate+" 00:00:00.000')");
            }
            ResultSet resultSet = statement.getResultSet();

            dailySalesReportTable.setModel(DbUtils.resultSetToTableModel(resultSet));
        } catch (SQLException ex) {
            Logger.getLogger(Manage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void LoadStockReportTable(String search) {
        //salesReportTable data load
        JTableHeader header = stockTable.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 14));
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            if (search.equals("All")) {
                statement.execute("SELECT ID, Name, UnitCost, Price, Qnt, ServiceUnit, LotNo FROM Stock");
            } else {
                statement.execute("SELECT ID, Name, UnitCost, Price, Qnt, ServiceUnit, LotNo FROM Stock  WHERE ID like '%" + search + "%' OR Name like '%" + search + "%'");
            }
            ResultSet resultSet = statement.getResultSet();

            stockTable.setModel(DbUtils.resultSetToTableModel(resultSet));
        } catch (SQLException ex) {
            Logger.getLogger(Manage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void ShowServiceDetails(int invoiceID) {
        ShowServiceDetails showServiceDetails = new ShowServiceDetails(invoiceID);
        showServiceDetails.setObject(this, dashboard );
        showServiceDetails.setLocationRelativeTo(null);
        showServiceDetails.setExtendedState(JFrame.MAXIMIZED_BOTH);
        showServiceDetails.setBackground(new Color(0, 0, 0, 150));
        showServiceDetails.setVisible(true);
    }
    
    public void ShowEnteredVehicleDetails(int invoiceID) {
        EnteredVehicleDetails enteredVehicleDetails = new EnteredVehicleDetails(invoiceID);
        enteredVehicleDetails.setObject(this, dashboard );
        enteredVehicleDetails.setLocationRelativeTo(null);
        enteredVehicleDetails.setExtendedState(JFrame.MAXIMIZED_BOTH);
        enteredVehicleDetails.setBackground(new Color(0, 0, 0, 150));
        enteredVehicleDetails.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cashPayments;
    private javax.swing.JPanel dailyReport;
    private button.MyButton dailyReportButton;
    private javax.swing.JTable dailySalesReportTable;
    private javax.swing.JPanel departedVehiclesCard;
    private javax.swing.JTable departedVehiclesTable;
    private javax.swing.JPanel enterdVehiclesCard;
    private javax.swing.JTable enterdVehiclesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel openDrawerAmount;
    private javax.swing.JLabel otherPayments;
    private javax.swing.JPanel panelCards;
    private javax.swing.JPanel salesReport;
    private button.MyButton salesReportButton;
    private javax.swing.JTable salesReportTable;
    private fosalgo.FTextField searchDailySalesReport;
    private fosalgo.FTextField searchDepVehicle;
    private fosalgo.FTextField searchEntVehicle;
    private fosalgo.FTextField searchSalesReport;
    private fosalgo.FTextField searchStock;
    private button.MyButton showDepartedVehiclePaneButton;
    private button.MyButton showEnterdVehiclePaneButton;
    private javax.swing.JPanel stockReport;
    private button.MyButton stockReportButton;
    private javax.swing.JTable stockTable;
    // End of variables declaration//GEN-END:variables
}
