/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reports;

import DBConnect.DBconnect;
import Dashboard.Dashboard;
import Reports.Templates.ProductItem;
import Reports.Templates.ServiceChargeItem;
import Vehicles.Vehicles;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Umindu
 */
public class ShowServiceDetails extends javax.swing.JFrame {

    /**
     * Creates new form CancelService
     */
    
    ArrayList<ArrayList<String> > allServicesList =  new ArrayList< >(); 
    ArrayList<ArrayList<String> > allProductList =  new ArrayList< >();
    
    private Reports reports;
    private Dashboard dashboard;
    
    public ShowServiceDetails(int invoiceID) { 
        setUndecorated(true);
        initComponents();
        
        serAndProPanel4.setLayout(new MigLayout("inset 0, fillx, wrap", "[fill]"));
        
        //close window
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            statement.execute("SELECT * FROM VehicleDetails WHERE InvoiceNo = '"+invoiceID+"'");
            ResultSet resultSet = statement.getResultSet();
            
            if(resultSet.next()){
                invoiceNo.setText(String.valueOf(invoiceID));
                VehicleRegNo.setText(resultSet.getString("VehicleNo"));
                ownerName.setText(resultSet.getString("OwnerName"));
                ownerPhone.setText(resultSet.getString("Phone"));
                vehicleType.setText(resultSet.getString("VehicleType"));
                description.setText(resultSet.getString("Description"));
                
                Date date = resultSet.getDate("Date");
                dateLable.setText("Date : "+date);
                
                Date time = resultSet.getTime("Date");
                timeLabel.setText("Time : "+time);
            }
            
            statement.execute("SELECT * FROM PaymentDetails WHERE InvoiceID = '"+invoiceID+"'");
            ResultSet resultSet2 = statement.getResultSet();
            
            if(resultSet2.next()){
                subTotal.setText("Rs. "+resultSet2.getString("SubTotal"));
                if(resultSet2.getBoolean("DiscountMethod")){
                    discount.setText("(%)  "+resultSet2.getString("Discount"));
                }else{
                    discount.setText("(Rs.)  "+resultSet2.getString("Discount"));
                }
                payableAmount.setText("Rs. "+resultSet2.getString("PayableAmount"));
                cashPayment.setText("Rs. "+resultSet2.getString("CashPayAmount"));
                cardPayment.setText("Rs. "+resultSet2.getString("CardPayAmount"));
                cardBillNo.setText("#"+resultSet2.getString("CardBillNumber"));
                qrPayment.setText("Rs. "+resultSet2.getString("QRPayAmount"));
                balance.setText("Rs. "+resultSet2.getString("Balance"));
                note.setText(resultSet2.getString("Note"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ShowServiceDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LoadVehicleServiceList(invoiceID);
    }

    private ShowServiceDetails() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        dateLable = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CancelButton = new button.MyButton();
        invoiceNo = new fosalgo.FTextField();
        jLabel6 = new javax.swing.JLabel();
        ActionButton = new button.MyButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        serAndProPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        VehicleRegNo = new javax.swing.JLabel();
        ownerName = new javax.swing.JLabel();
        ownerPhone = new javax.swing.JLabel();
        vehicleType = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        subTotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        discount = new javax.swing.JLabel();
        payableAmount = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cashPayment = new javax.swing.JLabel();
        cardPayment = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cardBillNo = new javax.swing.JLabel();
        qrPayment = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ActionButton1 = new button.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        dateLable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dateLable.setText("Date : 2023-04-03  ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Phone No: ");

        timeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        timeLabel.setText("Time : 12:45");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Description :");

        CancelButton.setText("Cancel");
        CancelButton.setBorderColor(new java.awt.Color(13, 180, 185));
        CancelButton.setBorderPainted(false);
        CancelButton.setColorClick(new java.awt.Color(184, 248, 250));
        CancelButton.setColorOver(new java.awt.Color(184, 248, 250));
        CancelButton.setFocusPainted(false);
        CancelButton.setFocusable(false);
        CancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CancelButton.setRadius(20);
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        invoiceNo.setFocusable(false);
        invoiceNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        invoiceNo.setRadius(20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Vehicle Type :");

        ActionButton.setBackground(new java.awt.Color(250, 184, 184));
        ActionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/trash.png"))); // NOI18N
        ActionButton.setText("Cancel Service");
        ActionButton.setBorderColor(new java.awt.Color(185, 12, 12));
        ActionButton.setBorderPainted(false);
        ActionButton.setColor(new java.awt.Color(250, 184, 184));
        ActionButton.setColorClick(new java.awt.Color(244, 125, 125));
        ActionButton.setColorOver(new java.awt.Color(244, 126, 126));
        ActionButton.setFocusPainted(false);
        ActionButton.setFocusable(false);
        ActionButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ActionButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ActionButton.setRadius(20);
        ActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionButtonActionPerformed(evt);
            }
        });

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setBorder(null);
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        serAndProPanel4.setBackground(new java.awt.Color(246, 246, 246));
        serAndProPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        javax.swing.GroupLayout serAndProPanel4Layout = new javax.swing.GroupLayout(serAndProPanel4);
        serAndProPanel4.setLayout(serAndProPanel4Layout);
        serAndProPanel4Layout.setHorizontalGroup(
            serAndProPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        serAndProPanel4Layout.setVerticalGroup(
            serAndProPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        jScrollPane6.setViewportView(serAndProPanel4);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Vehicle Registration No :");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Invoice No : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Owner Name :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Vehicle Details");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Payments Details");

        VehicleRegNo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        VehicleRegNo.setText(" ");

        ownerName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ownerName.setText(" ");

        ownerPhone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ownerPhone.setText(" ");

        vehicleType.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        vehicleType.setText(" ");

        description.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        description.setText(" ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Sub Total :");

        subTotal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        subTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        subTotal.setText("Rs. 0.00");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Discount :");

        discount.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        discount.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        discount.setText("Rs. 0.00");

        payableAmount.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        payableAmount.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        payableAmount.setText("Rs. 0.00");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Payable Amount :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Cash Payment :");

        cashPayment.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cashPayment.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cashPayment.setText("Rs. 0.00");

        cardPayment.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cardPayment.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cardPayment.setText("Rs. 0.00");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Card Payment :");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setText("Card Bill No :");

        cardBillNo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cardBillNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cardBillNo.setText("#");

        qrPayment.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        qrPayment.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        qrPayment.setText("Rs. 0.00");

        balance.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        balance.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        balance.setText("Rs. 0.00");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setText("Note :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setText("Balance :");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setText("QR Payment :");

        note.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        note.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        note.setText("note");

        ActionButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pencil.png"))); // NOI18N
        ActionButton1.setText("Change Service");
        ActionButton1.setBorderColor(new java.awt.Color(12, 185, 35));
        ActionButton1.setBorderPainted(false);
        ActionButton1.setColor(new java.awt.Color(184, 250, 203));
        ActionButton1.setColorClick(new java.awt.Color(126, 244, 129));
        ActionButton1.setColorOver(new java.awt.Color(126, 244, 172));
        ActionButton1.setFocusPainted(false);
        ActionButton1.setFocusable(false);
        ActionButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ActionButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ActionButton1.setRadius(20);
        ActionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateLable)
                        .addGap(27, 27, 27)
                        .addComponent(timeLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(note, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator1))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(vehicleType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ownerPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ownerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(payableAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(subTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(discount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cashPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cardPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cardBillNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(qrPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator2)))
                                        .addGap(20, 20, 20))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(VehicleRegNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)))
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ActionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ActionButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(invoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLable)
                    .addComponent(timeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(VehicleRegNo))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(ownerName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(vehicleType))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(description)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(ownerPhone)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(subTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(discount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(payableAmount))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cashPayment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cardPayment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cardBillNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(qrPayment))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(balance))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(note))
                        .addGap(96, 96, 96))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane6)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ActionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ActionButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionButtonActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null,"Sure? Cancel this service?", "Cancel Service", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            try {
                Statement statement = DBconnect.connectToDB().createStatement();
                statement.execute("DELETE FROM VehicleDetails WHERE InvoiceNo = '"+ invoiceNo.getText() +"'");
                statement.execute("DELETE FROM SoldProducts WHERE InvoiceID = '"+ invoiceNo.getText() +"'");
                statement.execute("DELETE FROM ServiceCharges WHERE InvoiceID = '"+ invoiceNo.getText() +"'");
            } catch (SQLException ex) {
                Logger.getLogger(ShowServiceDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            reports.LoadEnterdVehiclesTable("All");
            reports.LoadDepartedVehiclesTable("All");
            this.dispose();
        }
    }//GEN-LAST:event_ActionButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ActionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionButton1ActionPerformed
        dashboard.EditServiceAndProduct(Integer.parseInt(invoiceNo.getText()));
        this.dispose();
    }//GEN-LAST:event_ActionButton1ActionPerformed

    public void setObject(Reports reports, Dashboard dashboard){
        this.reports = reports;
        this.dashboard = dashboard;
    }
        
    public void RefrashSerAndProPanel(){
        serAndProPanel4.removeAll();
        for (int i = 0; i < allServicesList.size(); i++) {
            String name = allServicesList.get(i).get(0);
            String charge = allServicesList.get(i).get(1);
            serAndProPanel4.add(new ServiceChargeItem(name, charge)); 
            
            for (int j = 0; j < allProductList.size(); j++) {
                if(allProductList.get(j).get(5).equals(name)){
                    String id = allProductList.get(j).get(0);
                    String proname = allProductList.get(j).get(1);
                    float price = Float.parseFloat(allProductList.get(j).get(2));
                    float qnt = Float.parseFloat(allProductList.get(j).get(3));
                    float total = Float.parseFloat(allProductList.get(j).get(4));
                    serAndProPanel4.add(new ProductItem(id, proname, price, qnt, total));  
                }
            } 
        } 
        
        //productListPanel refresh
        serAndProPanel4.invalidate();
        serAndProPanel4.validate();
        serAndProPanel4.repaint();
    }
    
    public void LoadVehicleServiceList(int invoiceID){
        allServicesList.clear();
        allProductList.clear();
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            statement.execute("SELECT * FROM ServiceCharges WHERE InvoiceID = '"+ invoiceID +"'");
            ResultSet resultSet = statement.getResultSet();
            while(resultSet.next()){
                ArrayList<String> serviceList =  new ArrayList<>();
                serviceList.add(resultSet.getString("ServiceUnit"));
                serviceList.add(resultSet.getString("ServiceCharge"));
                allServicesList.add(serviceList);
            }
            for(int i=0; i < allServicesList.size(); i++){
                String serUnit = allServicesList.get(i).get(0);
                Statement statement2 = DBconnect.connectToDB().createStatement();
                statement2.execute("SELECT * FROM SoldProducts WHERE InvoiceID = '"+ invoiceID +"' AND ServiceUnit = '"+ serUnit +"'");
                ResultSet resultSetProducts = statement2.getResultSet();
                while(resultSetProducts.next()){
                    ArrayList<String> productList =  new ArrayList<>();
                    productList.add(resultSetProducts.getString("ProductID"));
                    productList.add(resultSetProducts.getString("Name"));
                    productList.add(resultSetProducts.getString("Price"));
                    productList.add(resultSetProducts.getString("Qnt"));
                    productList.add(resultSetProducts.getString("Total"));
                    productList.add(resultSetProducts.getString("ServiceUnit"));
                    allProductList.add(productList);
                }
            }
            RefrashSerAndProPanel();
        } catch (SQLException ex) {
            Logger.getLogger(Vehicles.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowServiceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowServiceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowServiceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowServiceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowServiceDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.MyButton ActionButton;
    private button.MyButton ActionButton1;
    private button.MyButton CancelButton;
    private javax.swing.JLabel VehicleRegNo;
    private javax.swing.JLabel balance;
    private javax.swing.JLabel cardBillNo;
    private javax.swing.JLabel cardPayment;
    private javax.swing.JLabel cashPayment;
    private javax.swing.JLabel dateLable;
    private javax.swing.JLabel description;
    private javax.swing.JLabel discount;
    private fosalgo.FTextField invoiceNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel note;
    private javax.swing.JLabel ownerName;
    private javax.swing.JLabel ownerPhone;
    private javax.swing.JLabel payableAmount;
    private javax.swing.JLabel qrPayment;
    private javax.swing.JPanel serAndProPanel4;
    private javax.swing.JLabel subTotal;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel vehicleType;
    // End of variables declaration//GEN-END:variables
}
