/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Home;

import DBConnect.DBconnect;
import Manage.Manage;
import Payments.Payments;
import Reports.CancelService;
import Vehicles.Vehicles;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.EncodeHintType;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.common.HybridBinarizer;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.border.MatteBorder;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Umindu
 */
public class Home extends javax.swing.JInternalFrame implements Runnable, ThreadFactory {

    /**
     * Creates new form Home
     */
    private DefaultListModel ListModel;

    private Home home;

    private ImageIcon qrImg;

    private boolean discountPercentage = true;

    private float subTotalCal = 0;

    private float payableAmountCal = 0;

    private boolean edited = false;

    ArrayList<ArrayList<String>> allServicesList = new ArrayList<>();
    ArrayList<ArrayList<String>> allProductList = new ArrayList<>();
    ArrayList<String> removeProductList = new ArrayList<>();
    ArrayList<String> removeServiceList = new ArrayList<>();
    
    private WebcamPanel campanel = null;
    private Webcam webcam = null;
    private Executor executor = Executors.newSingleThreadExecutor(this);

    public Home() {
        initComponents();

        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);

        sidePanel.setBorder(new MatteBorder(0, 10, 0, 0, new Color(242, 242, 242)));

        // add data Vehical Type ComboBox
        try {
            VehicleTypeComboBox.removeAllItems();
            Statement statement = DBconnect.connectToDB().createStatement();
            statement.execute("Select Name From VehicleType");
            ResultSet resultSet = statement.getResultSet();
            while (resultSet.next()) {
                VehicleTypeComboBox.addItem(resultSet.getString("Name"));
            }
            VehicleTypeComboBox.addItem("Other");
        } catch (SQLException ex) {
            Logger.getLogger(Manage.class.getName()).log(Level.SEVERE, null, ex);
        }

        //set invoice number
        setInvoiceNo();

        //search menu
        searchMenu.add(searchPanel);
        ListModel = new DefaultListModel();
        searchPanelList.setModel(ListModel);

        serAndProPanel.setLayout(new MigLayout("inset 0, fillx, wrap", "[fill]"));

        showDate();
        showTime();
        
        initWebcam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        searchPanelList = new javax.swing.JList<>();
        searchMenu = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        progressButton = new button.MyButton();
        sidePanel = new javax.swing.JPanel();
        invoiceSearch = new fosalgo.FTextField();
        invoiceNoLable = new javax.swing.JLabel();
        progressButton1 = new button.MyButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        serAndProPanel = new javax.swing.JPanel();
        payableAmount = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        discount = new fosalgo.FTextField();
        discountToggle = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        subTotal = new javax.swing.JLabel();
        cancelButton1 = new button.MyButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        ownerPhone = new fosalgo.FTextField();
        invoiceNo = new fosalgo.FTextField();
        ownerName = new fosalgo.FTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new CustomComponents.MyTextArea();
        VehicleRegNo = new fosalgo.FTextField();
        VehicleTypeComboBox = new CustomComponents.Combobox();
        timeLabel = new javax.swing.JLabel();
        cancelButton = new button.MyButton();
        qrCode = new javax.swing.JLabel();
        webCamOpenWindow = new javax.swing.JPanel();

        searchPanelList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchPanelList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchPanelListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(searchPanelList);

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );

        searchMenu.setFocusable(false);

        setBorder(null);
        setVisible(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Invoice No : ");

        dateLable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dateLable.setText("Date : 2023-04-03  ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Vehicle Registration No :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Owner Name :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Description :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Vehicle Type :");

        progressButton.setBackground(new java.awt.Color(184, 248, 250));
        progressButton.setText("Add Process");
        progressButton.setBorderColor(new java.awt.Color(13, 180, 185));
        progressButton.setBorderPainted(false);
        progressButton.setColor(new java.awt.Color(184, 248, 250));
        progressButton.setColorClick(new java.awt.Color(126, 240, 244));
        progressButton.setColorOver(new java.awt.Color(126, 240, 244));
        progressButton.setFocusPainted(false);
        progressButton.setFocusable(false);
        progressButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        progressButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        progressButton.setRadius(20);
        progressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressButtonActionPerformed(evt);
            }
        });

        sidePanel.setBackground(new java.awt.Color(255, 255, 255));

        invoiceSearch.setToolTipText("");
        invoiceSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        invoiceSearch.setRadius(20);
        invoiceSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                invoiceSearchKeyReleased(evt);
            }
        });

        invoiceNoLable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        invoiceNoLable.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        invoiceNoLable.setText("Invoice No");
        invoiceNoLable.setToolTipText("");
        invoiceNoLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        progressButton1.setForeground(new java.awt.Color(255, 255, 255));
        progressButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/angle-right.png"))); // NOI18N
        progressButton1.setText("Continue");
        progressButton1.setBorderColor(new java.awt.Color(13, 180, 185));
        progressButton1.setBorderPainted(false);
        progressButton1.setColor(new java.awt.Color(13, 180, 185));
        progressButton1.setColorClick(new java.awt.Color(11, 140, 144));
        progressButton1.setColorOver(new java.awt.Color(11, 140, 144));
        progressButton1.setFocusPainted(false);
        progressButton1.setFocusable(false);
        progressButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        progressButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        progressButton1.setIconTextGap(30);
        progressButton1.setRadius(20);
        progressButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        serAndProPanel.setBackground(new java.awt.Color(246, 246, 246));
        serAndProPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        javax.swing.GroupLayout serAndProPanelLayout = new javax.swing.GroupLayout(serAndProPanel);
        serAndProPanel.setLayout(serAndProPanelLayout);
        serAndProPanelLayout.setHorizontalGroup(
            serAndProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        serAndProPanelLayout.setVerticalGroup(
            serAndProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(serAndProPanel);

        payableAmount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        payableAmount.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        payableAmount.setText("Rs. 0.00");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Payable Amount :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Discount :");

        discount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        discount.setRadius(15);
        discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discountKeyReleased(evt);
            }
        });

        discountToggle.setBackground(new java.awt.Color(184, 248, 250));
        discountToggle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        discountToggle.setText("%");
        discountToggle.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        discountToggle.setBorderPainted(false);
        discountToggle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        discountToggle.setFocusPainted(false);
        discountToggle.setFocusable(false);
        discountToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountToggleActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Sub Total :");

        subTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subTotal.setText("Rs. 0.00");

        cancelButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        cancelButton1.setBorderColor(new java.awt.Color(13, 180, 185));
        cancelButton1.setBorderPainted(false);
        cancelButton1.setColorClick(new java.awt.Color(126, 240, 244));
        cancelButton1.setColorOver(new java.awt.Color(126, 240, 244));
        cancelButton1.setFocusPainted(false);
        cancelButton1.setFocusable(false);
        cancelButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cancelButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        cancelButton1.setRadius(20);
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(progressButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                        .addComponent(invoiceSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(invoiceNoLable, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                                .addComponent(discountToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(payableAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subTotal)))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceNoLable)
                    .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subTotal)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountToggle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payableAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Phone No: ");

        ownerPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ownerPhone.setRadius(20);

        invoiceNo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        invoiceNo.setFocusable(false);
        invoiceNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        invoiceNo.setRadius(20);

        ownerName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ownerName.setRadius(20);

        jScrollPane1.setBorder(null);

        description.setColumns(20);
        description.setRows(5);
        description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        description.setRadius(20);
        jScrollPane1.setViewportView(description);

        VehicleRegNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VehicleRegNo.setRadius(20);
        VehicleRegNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VehicleRegNoKeyReleased(evt);
            }
        });

        VehicleTypeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        timeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        timeLabel.setText("Time : 12:45");

        cancelButton.setText("Cancel");
        cancelButton.setBorderColor(new java.awt.Color(13, 180, 185));
        cancelButton.setBorderPainted(false);
        cancelButton.setColorClick(new java.awt.Color(126, 240, 244));
        cancelButton.setColorOver(new java.awt.Color(126, 240, 244));
        cancelButton.setFocusPainted(false);
        cancelButton.setFocusable(false);
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        cancelButton.setRadius(20);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        webCamOpenWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(qrCode, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(progressButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(ownerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                                        .addComponent(ownerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(VehicleRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(VehicleTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(webCamOpenWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(invoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addComponent(dateLable)
                                .addGap(21, 21, 21)
                                .addComponent(timeLabel)))
                        .addGap(6, 6, 6)))
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateLable)
                        .addComponent(timeLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VehicleRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ownerName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ownerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VehicleTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(webCamOpenWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(progressButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qrCode, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Read QR ................
    
    public void CloseWebCam(){
        webcam.close();  
    }
    
    private void initWebcam(){
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0);
        webcam.setViewSize(size);
        
        campanel = new WebcamPanel(webcam);
        campanel.setPreferredSize(size);
        campanel.setFPSDisplayed(true);
        campanel.setMirrored(true);
        
        webCamOpenWindow.add(campanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,250,250));
        
        executor.execute(this);  
    }
    
    @Override
    public void run() {
        do {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            Result result = null;
            BufferedImage image = null;

            if (webcam.isOpen()) {
                if ((image = webcam.getImage()) == null) {
                    continue;
                }

                LuminanceSource source = new BufferedImageLuminanceSource(image);
                BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

                try {
                    result = new MultiFormatReader().decode(bitmap);
                } catch (NotFoundException ex) {
//                    Logger.getLogger(Vehicles.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (result != null) {
//                Toolkit.getDefaultToolkit().beep();
//                String[] invoiceno = result.getText().split(",");
//                home.QRCodeRead(invoiceno[0]);
                
                
                String[] invoiceno = result.getText().split(",");
                if(!invoiceno[0].equals(invoiceNoLable.getText().substring(1))){
                    Toolkit.getDefaultToolkit().beep();
                    home.QRCodeRead(invoiceno[0]);
                }
            }
        } while (true);
    }
   @Override
    public Thread newThread(Runnable r) {
        Thread t = new Thread(r, "My Thread");
        t.setDaemon(true);
        return t;
    }
    
    //Read QR ................
    
    
    
    public void setObject(Home home) {
        this.home = home;
    }

    public void showDate() {
        SimpleDateFormat fdate = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        dateLable.setText("Date - " + fdate.format(date));
    }

    public void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat ftime = new SimpleDateFormat("hh:mm:ss a");
                Date time = new Date();
                timeLabel.setText(ftime.format(time));
            }
        }).start();
    }

    public void generateQRCode() {
        OldQRimageDelete();

        try {
            String qrText = invoiceNo.getText() + "," + VehicleRegNo.getText();
            String imgPath = System.getProperty("user.dir") + "/QR/";
            String charset = "UTF-8";
            Map<EncodeHintType, ErrorCorrectionLevel> hashMap = new HashMap<>();
            hashMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
            generateQRcode(qrText, imgPath + qrText + ".png", charset, hashMap, 140, 140);
            qrImg = new ImageIcon("QR/" + qrText + ".png");
            qrCode.setIcon(qrImg);
        } catch (WriterException | IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void OldQRimageDelete() {
        File file = new File(System.getProperty("user.dir") + "/QR/");
        String[] S = file.list();
        for (String ss : S) {
            File f1 = new File(file, ss);
            f1.delete();
        }
    }

    public void generateQRcode(String data, String path, String charset, Map map, int h, int w) throws WriterException, IOException {
        BitMatrix matrix = new MultiFormatWriter().encode(new String(data.getBytes(charset), charset), BarcodeFormat.QR_CODE, w, h);
        MatrixToImageWriter.writeToFile(matrix, path.substring(path.lastIndexOf('.') + 1), new File(path));
    }

    public void RefrashSerAndProPanel() {
        serAndProPanel.removeAll();
        for (int i = 0; i < allServicesList.size(); i++) {
            String name = allServicesList.get(i).get(0);
            String charge = allServicesList.get(i).get(1);
            serAndProPanel.add(new ServiceChargeItem(this, name, charge));

            for (int j = 0; j < allProductList.size(); j++) {
                if (allProductList.get(j).get(5).equals(name)) {
                    String id = allProductList.get(j).get(0);
                    String proname = allProductList.get(j).get(1);
                    float price = Float.parseFloat(allProductList.get(j).get(2));
                    float qnt = Float.parseFloat(allProductList.get(j).get(3));
                    float total = Float.parseFloat(allProductList.get(j).get(4));
                    serAndProPanel.add(new ProductItem(this, id, proname, price, qnt, total));
                }
            }
        }

        //productListPanel refresh
        serAndProPanel.invalidate();
        serAndProPanel.validate();
        serAndProPanel.repaint();

        CalculateSubTotalPayableAmount();
    }

    private void CalculateSubTotalPayableAmount() {
        subTotalCal = 0;
        for (ArrayList Service : allServicesList) {
            subTotalCal = subTotalCal + Float.parseFloat((String) Service.get(1));
        }
        for (ArrayList Product : allProductList) {
            subTotalCal = subTotalCal + Float.parseFloat((String) Product.get(4));
        }

        subTotal.setText("Rs. " + String.valueOf(subTotalCal));

        if (!discount.getText().isEmpty()) {
            if (discountPercentage == true) {
                payableAmountCal = subTotalCal - ((subTotalCal * (Float.parseFloat(discount.getText()) / 100)));
                payableAmount.setText("Rs. " + String.valueOf(payableAmountCal));
            } else {
                payableAmountCal = subTotalCal - Float.parseFloat(discount.getText());
                payableAmount.setText("Rs. " + String.valueOf(payableAmountCal));
            }
        } else {
            payableAmountCal = subTotalCal;
            payableAmount.setText("Rs. " + String.valueOf(subTotalCal));
        }
    }

    private void setInvoiceNo() {
        //set invoice number
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            statement.execute("SELECT MAX(COALESCE(InvoiceNo, 0)) AS largest_value FROM VehicleDetails");
            ResultSet resultSet = statement.getResultSet();
            if (resultSet.next()) {
                int maxInvoiceID = resultSet.getInt(1);
                if (resultSet.wasNull()) {
                    invoiceNo.setText("1");
                } else {
                    invoiceNo.setText(String.valueOf(maxInvoiceID + 1));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void progressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressButtonActionPerformed
        // TODO add your handling code here:
        if (!VehicleRegNo.getText().isEmpty()) {
            Date currentDate = new Date();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String formattedDate = dateFormat.format(currentDate);

            String Vehicleregno = VehicleRegNo.getText();
            String ownername = ownerName.getText();
            String ownerphone = ownerPhone.getText();
            String Vehicletype = VehicleTypeComboBox.getSelectedItem().toString();
            String descriptions = description.getText();
            try {
                Statement statement = DBconnect.connectToDB().createStatement();
                statement.execute("INSERT INTO VehicleDetails (Date, VehicleNo, OwnerName, Phone, VehicleType, States, Description) VALUES('" + formattedDate + "', '" + Vehicleregno + "', '" + ownername + "', '" + ownerphone + "', '" + Vehicletype + "', 'Processing', '" + descriptions + "')");
                System.out.println("Vehicle added successfully");

                VehicleRegNo.setText("");
                ownerName.setText("");
                ownerPhone.setText("");
                description.setText("");
                VehicleTypeComboBox.setSelectedIndex(0);

                setInvoiceNo();
            } catch (SQLException ex) {
                Logger.getLogger(Manage.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Vehicle add unsuccessful !, try again ");
            }
        }
    }//GEN-LAST:event_progressButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        VehicleRegNo.setText("");
        ownerName.setText("");
        ownerPhone.setText("");
        description.setText("");
        VehicleTypeComboBox.setSelectedIndex(0);

        setInvoiceNo();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void searchPanelListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPanelListMouseClicked
        // TODO add your handling code here:
        ClearSidePane();

        invoiceNoLable.setText("#" + searchPanelList.getSelectedValue());
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            statement.execute("SELECT * FROM ServiceCharges WHERE InvoiceID = '" + searchPanelList.getSelectedValue() + "'");
            ResultSet resultSet = statement.getResultSet();
            while (resultSet.next()) {
                ArrayList<String> serviceList = new ArrayList<String>();
                serviceList.add(resultSet.getString("ServiceUnit"));
                serviceList.add(resultSet.getString("ServiceCharge"));
                allServicesList.add(serviceList);
            }
            for (int i = 0; i < allServicesList.size(); i++) {
                String serUnit = allServicesList.get(i).get(0);
                Statement statement2 = DBconnect.connectToDB().createStatement();
                statement2.execute("SELECT * FROM SoldProducts WHERE InvoiceID = '" + searchPanelList.getSelectedValue() + "' AND ServiceUnit = '" + serUnit + "'");
                ResultSet resultSetProducts = statement2.getResultSet();
                while (resultSetProducts.next()) {
                    ArrayList<String> productList = new ArrayList<>();
                    productList.add(resultSetProducts.getString("ProductID"));
                    productList.add(resultSetProducts.getString("Name"));
                    productList.add(resultSetProducts.getString("Price"));
                    productList.add(resultSetProducts.getString("Qnt"));
                    productList.add(resultSetProducts.getString("Total"));
                    productList.add(resultSetProducts.getString("ServiceUnit"));
                    allProductList.add(productList);
                }
            }
            RefrashSerAndProPanel();
        } catch (SQLException ex) {
            Logger.getLogger(Vehicles.class.getName()).log(Level.SEVERE, null, ex);
        }

        searchMenu.setVisible(false);
        invoiceSearch.setText("");
    }//GEN-LAST:event_searchPanelListMouseClicked

    public void QRCodeRead(String invoiceID) {
        // TODO add your handling code here:
        ClearSidePane();

        invoiceNoLable.setText("#" + invoiceID);
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            statement.execute("SELECT * FROM ServiceCharges WHERE InvoiceID = '" + invoiceID + "'");
            ResultSet resultSet = statement.getResultSet();
            while (resultSet.next()) {
                ArrayList<String> serviceList = new ArrayList<String>();
                serviceList.add(resultSet.getString("ServiceUnit"));
                serviceList.add(resultSet.getString("ServiceCharge"));
                allServicesList.add(serviceList);
            }
            for (int i = 0; i < allServicesList.size(); i++) {
                String serUnit = allServicesList.get(i).get(0);
                Statement statement2 = DBconnect.connectToDB().createStatement();
                statement2.execute("SELECT * FROM SoldProducts WHERE InvoiceID = '" + invoiceID + "' AND ServiceUnit = '" + serUnit + "'");
                ResultSet resultSetProducts = statement2.getResultSet();
                while (resultSetProducts.next()) {
                    ArrayList<String> productList = new ArrayList<>();
                    productList.add(resultSetProducts.getString("ProductID"));
                    productList.add(resultSetProducts.getString("Name"));
                    productList.add(resultSetProducts.getString("Price"));
                    productList.add(resultSetProducts.getString("Qnt"));
                    productList.add(resultSetProducts.getString("Total"));
                    productList.add(resultSetProducts.getString("ServiceUnit"));
                    allProductList.add(productList);
                }
            }
            RefrashSerAndProPanel();
        } catch (SQLException ex) {
            Logger.getLogger(Vehicles.class.getName()).log(Level.SEVERE, null, ex);
        }

        searchMenu.setVisible(false);
        invoiceSearch.setText("");
    }

    private void invoiceSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoiceSearchKeyReleased
        // TODO add your handling code here:
        String search = invoiceSearch.getText().trim();
        if (!search.equals("")) {
            ListModel.removeAllElements();
            try {
                Statement statement = DBconnect.connectToDB().createStatement();
                statement.execute("SELECT InvoiceNo FROM VehicleDetails WHERE InvoiceNo LIKE '%" + search + "%' AND States = 'Processing'");
                ResultSet resultSet = statement.getResultSet();
                if (resultSet.next()) {
                    searchMenu.show(invoiceSearch, 0, invoiceSearch.getHeight());
                    searchMenu.setPopupSize(170, 170);
                    ListModel.addElement(resultSet.getString("InvoiceNo"));
                } else {
                    searchMenu.setVisible(false);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Vehicles.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            searchMenu.setVisible(false);
        }
    }//GEN-LAST:event_invoiceSearchKeyReleased

    public void ClearSidePane() {
        allServicesList.clear();
        allProductList.clear();
        serAndProPanel.removeAll();
        subTotalCal = 0;
        payableAmountCal = 0;
        discount.setText("");
        invoiceNoLable.setText("Invoice No");
        edited = false;

        RefrashSerAndProPanel();
    }

    private void progressButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressButton1ActionPerformed
        // TODO add your handling code here:
        String invoiceID = invoiceNoLable.getText().substring(1);

        if (edited == true) {
            int result = JOptionPane.showConfirmDialog(null, "Sure? Update this?", "Update", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                try {
                    Statement statement = DBconnect.connectToDB().createStatement();
                    //remove services
                    if (!removeServiceList.isEmpty()) {
                        for (String index : removeServiceList) {
                            statement.execute("DELETE ServiceCharges WHERE InvoiceID = '" + invoiceID + "' AND ServiceUnit = '" + index + "'");
                        }
                    }
                    //update service
                    if (!allServicesList.isEmpty()) {
                        for (ArrayList Service : allServicesList) {
                            statement.execute("UPDATE ServiceCharges SET ServiceCharge = '" + Service.get(1) + "' WHERE InvoiceID = '" + invoiceID + "' AND ServiceUnit = '" + Service.get(0) + "'");
                        }
                    }
                    //remove products
                    if (!removeProductList.isEmpty()) {
                        for (String index : removeProductList) {
                            statement.execute("DELETE SoldProducts WHERE InvoiceID = '" + invoiceID + "' AND ProductID = '" + index + "'");
                        }
                    }
                    //update products
                    if (!allProductList.isEmpty()) {
                        for (ArrayList Product : allProductList) {
                            statement.execute("UPDATE SoldProducts SET Qnt = '" + Product.get(3) + "', Total = '" + Product.get(4) + "' WHERE InvoiceID = '" + invoiceID + "' AND ProductID = '" + Product.get(0) + "'");
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(CancelService.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        edited = false;
        if (!invoiceNoLable.getText().equals("Invoice No")) {
            Payments payments = new Payments(invoiceNoLable.getText().substring(1), subTotalCal, discountPercentage, discount.getText().isEmpty() ? "0" : discount.getText(), payableAmountCal);
            payments.setLocationRelativeTo(null);
            payments.setExtendedState(JFrame.MAXIMIZED_BOTH);
            payments.setBackground(new Color(0, 0, 0, 150));
            payments.setVisible(true);

            payments.setObject(this);
        }


    }//GEN-LAST:event_progressButton1ActionPerformed

    private void VehicleRegNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VehicleRegNoKeyReleased
        // TODO add your handling code here:
        generateQRCode();

        String text = VehicleRegNo.getText();
        char lastLetter = text.charAt(text.length() - 1);
        if (lastLetter >= '0' && lastLetter <= '9') {
            if (!VehicleRegNo.getText().contains("-")) {
                VehicleRegNo.setText(VehicleRegNo.getText().substring(0, VehicleRegNo.getText().length() - 1) + '-' + lastLetter);
            }
        }

    }//GEN-LAST:event_VehicleRegNoKeyReleased

    private void discountToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountToggleActionPerformed
        // TODO add your handling code here:
        if (discountToggle.isSelected()) {
            discountToggle.setText("Rs.");
            discountPercentage = false;
        } else {
            discountToggle.setText("%");
            discountPercentage = true;
        }

        if (!discount.getText().isEmpty()) {
            if (discountPercentage == true) {
                payableAmountCal = subTotalCal - ((subTotalCal * (Float.parseFloat(discount.getText()) / 100)));
                payableAmount.setText("Rs. " + String.valueOf(payableAmountCal));
            } else {
                payableAmountCal = subTotalCal - Float.parseFloat(discount.getText());
                payableAmount.setText("Rs. " + String.valueOf(payableAmountCal));
            }
        } else {
            payableAmountCal = subTotalCal;
            payableAmount.setText("Rs. " + String.valueOf(subTotalCal));
        }
    }//GEN-LAST:event_discountToggleActionPerformed

    private void discountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountKeyReleased
        // TODO add your handling code here:
        if (!discount.getText().isEmpty()) {
            if (discountPercentage == true) {
                payableAmountCal = subTotalCal - ((subTotalCal * (Float.parseFloat(discount.getText()) / 100)));
                payableAmount.setText("Rs. " + String.valueOf(payableAmountCal));
            } else {
                payableAmountCal = subTotalCal - Float.parseFloat(discount.getText());
                payableAmount.setText("Rs. " + String.valueOf(payableAmountCal));
            }
        } else {
            payableAmountCal = subTotalCal;
            payableAmount.setText("Rs. " + String.valueOf(subTotalCal));
        }
    }//GEN-LAST:event_discountKeyReleased

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
        // TODO add your handling code here:
        ClearSidePane();
    }//GEN-LAST:event_cancelButton1ActionPerformed

    public void EditServiceAndProduct(int InvoiceID) {
        ClearSidePane();

        invoiceNoLable.setText("#" + InvoiceID);
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            statement.execute("SELECT * FROM ServiceCharges WHERE InvoiceID = '" + InvoiceID + "'");
            ResultSet resultSet = statement.getResultSet();
            while (resultSet.next()) {
                ArrayList<String> serviceList = new ArrayList<>();
                serviceList.add(resultSet.getString("ServiceUnit"));
                serviceList.add(resultSet.getString("ServiceCharge"));
                allServicesList.add(serviceList);
            }
            for (int i = 0; i < allServicesList.size(); i++) {
                String serUnit = allServicesList.get(i).get(0);
                Statement statement2 = DBconnect.connectToDB().createStatement();
                statement2.execute("SELECT * FROM SoldProducts WHERE InvoiceID = '" + InvoiceID + "' AND ServiceUnit = '" + serUnit + "'");
                ResultSet resultSetProducts = statement2.getResultSet();
                while (resultSetProducts.next()) {
                    ArrayList<String> productList = new ArrayList<>();
                    productList.add(resultSetProducts.getString("ProductID"));
                    productList.add(resultSetProducts.getString("Name"));
                    productList.add(resultSetProducts.getString("Price"));
                    productList.add(resultSetProducts.getString("Qnt"));
                    productList.add(resultSetProducts.getString("Total"));
                    productList.add(resultSetProducts.getString("ServiceUnit"));
                    allProductList.add(productList);
                }
            }

            try {
                Statement statement3 = DBconnect.connectToDB().createStatement();
                statement3.execute("SELECT Discount, DiscountMethod FROM PaymentDetails WHERE InvoiceID = '" + InvoiceID + "'");
                ResultSet resultSet3 = statement3.getResultSet();
                if (resultSet3.next()) {
                    discount.setText(resultSet3.getString("Discount"));
                    discountPercentage = resultSet3.getBoolean("DiscountMethod");
                    discountToggle.setSelected(!discountPercentage);
                    discountToggleActionPerformed(null);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }

            RefrashSerAndProPanel();
        } catch (SQLException ex) {
            Logger.getLogger(Vehicles.class.getName()).log(Level.SEVERE, null, ex);
        }

        searchMenu.setVisible(false);
        invoiceSearch.setText("");
    }

    public void RemoveProduct(String id) {
        removeProductList.add(id);
        for (int i = 0; i < allProductList.size(); i++) {
            if (allProductList.get(i).get(0).equals(id)) {
                allProductList.remove(i);
            }
        }
        edited = true;
        RefrashSerAndProPanel();
        CalculateSubTotalPayableAmount();
    }

    public void UpdateProduct(ArrayList editProduct) {
        for (int i = 0; i < allProductList.size(); i++) {
            if (allProductList.get(i).get(0).equals(editProduct.get(0))) {
                allProductList.get(i).set(3, String.valueOf(editProduct.get(3)));
                allProductList.get(i).set(4, String.valueOf(editProduct.get(4)));
            }
        }
        edited = true;
        CalculateSubTotalPayableAmount();
    }

    public void RemoveService(String name) {
        for (int i = 0; i < allProductList.size(); i++) {
            if (allProductList.get(i).get(5).equals(name)) {
                JOptionPane.showMessageDialog(null, "First, remove these unit products !", "Remove", JOptionPane.ERROR_MESSAGE);
                break;
            } else {
                removeServiceList.add(name);
                for (int j = 0; j < allServicesList.size(); j++) {
                    if (allServicesList.get(j).get(0).equals(name)) {
                        allServicesList.remove(j);
                    }
                }
                RefrashSerAndProPanel();
                CalculateSubTotalPayableAmount();
            }
        }

        if (allProductList.isEmpty()) {
            removeServiceList.add(name);
            for (int j = 0; j < allServicesList.size(); j++) {
                if (allServicesList.get(j).get(0).equals(name)) {
                    allServicesList.remove(j);
                }
            }
            RefrashSerAndProPanel();
            CalculateSubTotalPayableAmount();
        }
        edited = true;
    }

    public void UpdateService(String name, String charge) {
        System.out.println(charge);
        for (int i = 0; i < allServicesList.size(); i++) {
            if (allServicesList.get(i).get(0).equals(name)) {
                allServicesList.get(i).set(1, charge);
            }
        }
        edited = true;
        CalculateSubTotalPayableAmount();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fosalgo.FTextField VehicleRegNo;
    private CustomComponents.Combobox VehicleTypeComboBox;
    private button.MyButton cancelButton;
    private button.MyButton cancelButton1;
    private javax.swing.JLabel dateLable;
    private CustomComponents.MyTextArea description;
    private fosalgo.FTextField discount;
    private javax.swing.JToggleButton discountToggle;
    private fosalgo.FTextField invoiceNo;
    private javax.swing.JLabel invoiceNoLable;
    private fosalgo.FTextField invoiceSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private fosalgo.FTextField ownerName;
    private fosalgo.FTextField ownerPhone;
    private javax.swing.JLabel payableAmount;
    private button.MyButton progressButton;
    private button.MyButton progressButton1;
    private javax.swing.JLabel qrCode;
    private javax.swing.JPopupMenu searchMenu;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JList<String> searchPanelList;
    private javax.swing.JPanel serAndProPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel subTotal;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JPanel webCamOpenWindow;
    // End of variables declaration//GEN-END:variables
}
