/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Payments;

import DBConnect.DBconnect;
import Home.Home;
import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.FocusManager;

/**
 *
 * @author Umindu
 */

public class Payments extends javax.swing.JFrame {
    
    private String invoiceNo;
    private float subTotalCal = 0;
    private boolean discountPercentage;
    private float discount;
    private float payableAmountCal = 0;
    private float balance = 0;
    
    private Home home;
    /**
     * Creates new form Payments
     */
    public Payments() {
        setUndecorated(true);
        initComponents();
    }

    public Payments(String invoiceNo, float subTotalCal, boolean discountPercentage, String discount, float payableAmountCal) {
        setUndecorated(true);
        initComponents();
        invoiceID.setText("Invoice No: #"+invoiceNo);
        payableAmount.setText("Total Payable Amount : Rs. "+payableAmountCal);
        this.invoiceNo = invoiceNo;
        this.subTotalCal = subTotalCal;
        this.discountPercentage = discountPercentage;
        this.discount = Float.parseFloat(discount);
        this.payableAmountCal = payableAmountCal;
        BalanceCalculate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        payableAmount = new javax.swing.JLabel();
        invoiceID = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        cashAmount = new fosalgo.FTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cardAmount = new fosalgo.FTextField();
        cardBillNo = new fosalgo.FTextField();
        jLabel8 = new javax.swing.JLabel();
        qrAmount = new fosalgo.FTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        balanceLable = new javax.swing.JLabel();
        myButton10 = new button.MyButton();
        jPanel3 = new javax.swing.JPanel();
        myButton1 = new button.MyButton();
        myButton2 = new button.MyButton();
        myButton3 = new button.MyButton();
        myButton4 = new button.MyButton();
        myButton5 = new button.MyButton();
        myButton6 = new button.MyButton();
        myButton7 = new button.MyButton();
        myButton8 = new button.MyButton();
        myButton9 = new button.MyButton();
        clearButton = new button.MyButton();
        myButton0 = new button.MyButton();
        dotButton = new button.MyButton();
        myButton00 = new button.MyButton();
        backspaceButton = new button.MyButton();
        conform = new button.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        payableAmount.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        payableAmount.setText("Total Payable Amount : Rs. 0.00");

        invoiceID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        invoiceID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        invoiceID.setText("Invoice No: #123435");
        invoiceID.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cash payment ");

        cashAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cashAmount.setName("cashAmount"); // NOI18N
        cashAmount.setRadius(10);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Amount :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Card payment");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Amount :");

        cardAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cardAmount.setName("cardAmount"); // NOI18N
        cardAmount.setRadius(10);

        cardBillNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cardBillNo.setName("cardBillNo"); // NOI18N
        cardBillNo.setRadius(10);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Card Bill No : ");

        qrAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qrAmount.setName("qrAmount"); // NOI18N
        qrAmount.setRadius(10);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Amount :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("QR payment ");

        balanceLable.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        balanceLable.setText("Balance : Rs. 0.00");

        myButton10.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        myButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/arrow-small-left.png"))); // NOI18N
        myButton10.setText("Back");
        myButton10.setBorderColor(new java.awt.Color(255, 255, 255));
        myButton10.setBorderPainted(false);
        myButton10.setColorClick(new java.awt.Color(184, 248, 250));
        myButton10.setColorOver(new java.awt.Color(184, 248, 250));
        myButton10.setFocusPainted(false);
        myButton10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        myButton10.setRadius(5);
        myButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cardAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cashAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cardBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(qrAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9))
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(0, 107, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(payableAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(balanceLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(myButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(invoiceID, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceID)
                    .addComponent(myButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(payableAmount)
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(46, 46, 46)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qrAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(balanceLable)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        myButton1.setText("1");
        myButton1.setBorderColor(new java.awt.Color(236, 240, 241));
        myButton1.setBorderPainted(false);
        myButton1.setColor(new java.awt.Color(236, 240, 241));
        myButton1.setColorClick(new java.awt.Color(184, 248, 250));
        myButton1.setColorOver(new java.awt.Color(184, 248, 250));
        myButton1.setFocusPainted(false);
        myButton1.setFocusable(false);
        myButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myButton1.setRadius(20);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        myButton2.setText("2");
        myButton2.setBorderColor(new java.awt.Color(236, 240, 241));
        myButton2.setBorderPainted(false);
        myButton2.setColor(new java.awt.Color(236, 240, 241));
        myButton2.setColorClick(new java.awt.Color(184, 248, 250));
        myButton2.setColorOver(new java.awt.Color(184, 248, 250));
        myButton2.setFocusPainted(false);
        myButton2.setFocusable(false);
        myButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myButton2.setRadius(20);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });

        myButton3.setText("3");
        myButton3.setBorderColor(new java.awt.Color(236, 240, 241));
        myButton3.setBorderPainted(false);
        myButton3.setColor(new java.awt.Color(236, 240, 241));
        myButton3.setColorClick(new java.awt.Color(184, 248, 250));
        myButton3.setColorOver(new java.awt.Color(184, 248, 250));
        myButton3.setFocusPainted(false);
        myButton3.setFocusable(false);
        myButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myButton3.setRadius(20);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });

        myButton4.setText("4");
        myButton4.setBorderColor(new java.awt.Color(236, 240, 241));
        myButton4.setBorderPainted(false);
        myButton4.setColor(new java.awt.Color(236, 240, 241));
        myButton4.setColorClick(new java.awt.Color(184, 248, 250));
        myButton4.setColorOver(new java.awt.Color(184, 248, 250));
        myButton4.setFocusPainted(false);
        myButton4.setFocusable(false);
        myButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myButton4.setRadius(20);
        myButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton4ActionPerformed(evt);
            }
        });

        myButton5.setText("5");
        myButton5.setBorderColor(new java.awt.Color(236, 240, 241));
        myButton5.setBorderPainted(false);
        myButton5.setColor(new java.awt.Color(236, 240, 241));
        myButton5.setColorClick(new java.awt.Color(184, 248, 250));
        myButton5.setColorOver(new java.awt.Color(184, 248, 250));
        myButton5.setFocusPainted(false);
        myButton5.setFocusable(false);
        myButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myButton5.setRadius(20);
        myButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton5ActionPerformed(evt);
            }
        });

        myButton6.setText("6");
        myButton6.setBorderColor(new java.awt.Color(236, 240, 241));
        myButton6.setBorderPainted(false);
        myButton6.setColor(new java.awt.Color(236, 240, 241));
        myButton6.setColorClick(new java.awt.Color(184, 248, 250));
        myButton6.setColorOver(new java.awt.Color(184, 248, 250));
        myButton6.setFocusPainted(false);
        myButton6.setFocusable(false);
        myButton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myButton6.setRadius(20);
        myButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton6ActionPerformed(evt);
            }
        });

        myButton7.setText("8");
        myButton7.setBorderColor(new java.awt.Color(236, 240, 241));
        myButton7.setBorderPainted(false);
        myButton7.setColor(new java.awt.Color(236, 240, 241));
        myButton7.setColorClick(new java.awt.Color(184, 248, 250));
        myButton7.setColorOver(new java.awt.Color(184, 248, 250));
        myButton7.setFocusPainted(false);
        myButton7.setFocusable(false);
        myButton7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myButton7.setRadius(20);
        myButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton7ActionPerformed(evt);
            }
        });

        myButton8.setText("9");
        myButton8.setBorderColor(new java.awt.Color(236, 240, 241));
        myButton8.setBorderPainted(false);
        myButton8.setColor(new java.awt.Color(236, 240, 241));
        myButton8.setColorClick(new java.awt.Color(184, 248, 250));
        myButton8.setColorOver(new java.awt.Color(184, 248, 250));
        myButton8.setFocusPainted(false);
        myButton8.setFocusable(false);
        myButton8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myButton8.setRadius(20);
        myButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton8ActionPerformed(evt);
            }
        });

        myButton9.setText("7");
        myButton9.setBorderColor(new java.awt.Color(236, 240, 241));
        myButton9.setBorderPainted(false);
        myButton9.setColor(new java.awt.Color(236, 240, 241));
        myButton9.setColorClick(new java.awt.Color(184, 248, 250));
        myButton9.setColorOver(new java.awt.Color(184, 248, 250));
        myButton9.setFocusPainted(false);
        myButton9.setFocusable(false);
        myButton9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myButton9.setRadius(20);
        myButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton9ActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.setBorderColor(new java.awt.Color(236, 240, 241));
        clearButton.setBorderPainted(false);
        clearButton.setColor(new java.awt.Color(236, 240, 241));
        clearButton.setColorClick(new java.awt.Color(184, 248, 250));
        clearButton.setColorOver(new java.awt.Color(184, 248, 250));
        clearButton.setFocusPainted(false);
        clearButton.setFocusable(false);
        clearButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clearButton.setRadius(20);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        myButton0.setText("0");
        myButton0.setBorderColor(new java.awt.Color(236, 240, 241));
        myButton0.setBorderPainted(false);
        myButton0.setColor(new java.awt.Color(236, 240, 241));
        myButton0.setColorClick(new java.awt.Color(184, 248, 250));
        myButton0.setColorOver(new java.awt.Color(184, 248, 250));
        myButton0.setFocusPainted(false);
        myButton0.setFocusable(false);
        myButton0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myButton0.setRadius(20);
        myButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton0ActionPerformed(evt);
            }
        });

        dotButton.setText(".");
        dotButton.setBorderColor(new java.awt.Color(236, 240, 241));
        dotButton.setBorderPainted(false);
        dotButton.setColor(new java.awt.Color(236, 240, 241));
        dotButton.setColorClick(new java.awt.Color(184, 248, 250));
        dotButton.setColorOver(new java.awt.Color(184, 248, 250));
        dotButton.setFocusPainted(false);
        dotButton.setFocusable(false);
        dotButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dotButton.setRadius(20);
        dotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotButtonActionPerformed(evt);
            }
        });

        myButton00.setText("00");
        myButton00.setBorderColor(new java.awt.Color(236, 240, 241));
        myButton00.setBorderPainted(false);
        myButton00.setColor(new java.awt.Color(236, 240, 241));
        myButton00.setColorClick(new java.awt.Color(184, 248, 250));
        myButton00.setColorOver(new java.awt.Color(184, 248, 250));
        myButton00.setFocusPainted(false);
        myButton00.setFocusable(false);
        myButton00.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myButton00.setRadius(20);
        myButton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton00ActionPerformed(evt);
            }
        });

        backspaceButton.setText("Backspace");
        backspaceButton.setBorderColor(new java.awt.Color(236, 240, 241));
        backspaceButton.setBorderPainted(false);
        backspaceButton.setColor(new java.awt.Color(236, 240, 241));
        backspaceButton.setColorClick(new java.awt.Color(184, 248, 250));
        backspaceButton.setColorOver(new java.awt.Color(184, 248, 250));
        backspaceButton.setFocusPainted(false);
        backspaceButton.setFocusable(false);
        backspaceButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backspaceButton.setRadius(20);
        backspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceButtonActionPerformed(evt);
            }
        });

        conform.setForeground(new java.awt.Color(255, 255, 255));
        conform.setText("Conform");
        conform.setBorderColor(new java.awt.Color(13, 180, 185));
        conform.setBorderPainted(false);
        conform.setColor(new java.awt.Color(13, 180, 185));
        conform.setColorClick(new java.awt.Color(11, 140, 144));
        conform.setColorOver(new java.awt.Color(11, 140, 144));
        conform.setFocusPainted(false);
        conform.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        conform.setRadius(20);
        conform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conformActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(myButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dotButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(myButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(myButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(myButton00, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(myButton0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(myButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(myButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(myButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(backspaceButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(myButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(myButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(myButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(myButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myButton00, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conform, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setObject(Home home){
        this.home = home;
    }
    
    private void BalanceCalculate(){
//        payableAmountCal  cashAmount  cardAmount  qrAmount  balance  balanceLable
        float cash;
        float card;
        float qr;
        
        if(!cashAmount.getText().isEmpty()){
            cash = Float.parseFloat(cashAmount.getText());
        }else{
            cash = 0;
        }
        if(!cardAmount.getText().isEmpty()){
            card = Float.parseFloat(cardAmount.getText());
        }else{
            card = 0;
        }
        if(!qrAmount.getText().isEmpty()){
            qr = Float.parseFloat(qrAmount.getText());
        }else{
            qr = 0;
        }
        
        balance = (card + qr + cash) - payableAmountCal;
        balanceLable.setText("Balance : Rs. "+balance);
    }
    
    private void myButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton10ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_myButton10ActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        // TODO add your handling code here:
        String focusOwner = FocusManager.getCurrentManager().getFocusOwner().getName();
        if(focusOwner == "cashAmount"){
            cashAmount.setText(cashAmount.getText()+"1");
        }else if(focusOwner == "cardAmount"){
            cardAmount.setText(cardAmount.getText()+"1");
        }else if(focusOwner == "cardBillNo"){
            cardBillNo.setText(cardBillNo.getText()+"1");
        }else if(focusOwner == "qrAmount"){
            qrAmount.setText(qrAmount.getText()+"1");
        }
        BalanceCalculate();
    }//GEN-LAST:event_myButton1ActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        // TODO add your handling code here:
        String focusOwner = FocusManager.getCurrentManager().getFocusOwner().getName();
        if(focusOwner == "cashAmount"){
            cashAmount.setText(cashAmount.getText()+"2");
        }else if(focusOwner == "cardAmount"){
            cardAmount.setText(cardAmount.getText()+"2");
        }else if(focusOwner == "cardBillNo"){
            cardBillNo.setText(cardBillNo.getText()+"2");
        }else if(focusOwner == "qrAmount"){
            qrAmount.setText(qrAmount.getText()+"2");
        }
        BalanceCalculate();
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        // TODO add your handling code here:
        String focusOwner = FocusManager.getCurrentManager().getFocusOwner().getName();
        if(focusOwner == "cashAmount"){
            cashAmount.setText(cashAmount.getText()+"3");
        }else if(focusOwner == "cardAmount"){
            cardAmount.setText(cardAmount.getText()+"3");
        }else if(focusOwner == "cardBillNo"){
            cardBillNo.setText(cardBillNo.getText()+"3");
        }else if(focusOwner == "qrAmount"){
            qrAmount.setText(qrAmount.getText()+"3");
        }
        BalanceCalculate();
    }//GEN-LAST:event_myButton3ActionPerformed

    private void myButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton4ActionPerformed
        // TODO add your handling code here:
        String focusOwner = FocusManager.getCurrentManager().getFocusOwner().getName();
        if(focusOwner == "cashAmount"){
            cashAmount.setText(cashAmount.getText()+"4");
        }else if(focusOwner == "cardAmount"){
            cardAmount.setText(cardAmount.getText()+"4");
        }else if(focusOwner == "cardBillNo"){
            cardBillNo.setText(cardBillNo.getText()+"4");
        }else if(focusOwner == "qrAmount"){
            qrAmount.setText(qrAmount.getText()+"4");
        }
        BalanceCalculate();
    }//GEN-LAST:event_myButton4ActionPerformed

    private void myButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton5ActionPerformed
        // TODO add your handling code here:
        String focusOwner = FocusManager.getCurrentManager().getFocusOwner().getName();
        if(focusOwner == "cashAmount"){
            cashAmount.setText(cashAmount.getText()+"5");
        }else if(focusOwner == "cardAmount"){
            cardAmount.setText(cardAmount.getText()+"5");
        }else if(focusOwner == "cardBillNo"){
            cardBillNo.setText(cardBillNo.getText()+"5");
        }else if(focusOwner == "qrAmount"){
            qrAmount.setText(qrAmount.getText()+"5");
        }
        BalanceCalculate();
    }//GEN-LAST:event_myButton5ActionPerformed

    private void myButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton6ActionPerformed
        // TODO add your handling code here:
        String focusOwner = FocusManager.getCurrentManager().getFocusOwner().getName();
        if(focusOwner == "cashAmount"){
            cashAmount.setText(cashAmount.getText()+"6");
        }else if(focusOwner == "cardAmount"){
            cardAmount.setText(cardAmount.getText()+"6");
        }else if(focusOwner == "cardBillNo"){
            cardBillNo.setText(cardBillNo.getText()+"6");
        }else if(focusOwner == "qrAmount"){
            qrAmount.setText(qrAmount.getText()+"6");
        }
        BalanceCalculate();
    }//GEN-LAST:event_myButton6ActionPerformed

    private void myButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton9ActionPerformed
        // TODO add your handling code here:
        String focusOwner = FocusManager.getCurrentManager().getFocusOwner().getName();
        if(focusOwner == "cashAmount"){
            cashAmount.setText(cashAmount.getText()+"7");
        }else if(focusOwner == "cardAmount"){
            cardAmount.setText(cardAmount.getText()+"7");
        }else if(focusOwner == "cardBillNo"){
            cardBillNo.setText(cardBillNo.getText()+"7");
        }else if(focusOwner == "qrAmount"){
            qrAmount.setText(qrAmount.getText()+"7");
        }
        BalanceCalculate();
    }//GEN-LAST:event_myButton9ActionPerformed

    private void myButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton7ActionPerformed
        // TODO add your handling code here:
        String focusOwner = FocusManager.getCurrentManager().getFocusOwner().getName();
        if(focusOwner == "cashAmount"){
            cashAmount.setText(cashAmount.getText()+"8");
        }else if(focusOwner == "cardAmount"){
            cardAmount.setText(cardAmount.getText()+"8");
        }else if(focusOwner == "cardBillNo"){
            cardBillNo.setText(cardBillNo.getText()+"8");
        }else if(focusOwner == "qrAmount"){
            qrAmount.setText(qrAmount.getText()+"8");
        }
        BalanceCalculate();
    }//GEN-LAST:event_myButton7ActionPerformed

    private void myButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton8ActionPerformed
        // TODO add your handling code here:
        String focusOwner = FocusManager.getCurrentManager().getFocusOwner().getName();
        if(focusOwner == "cashAmount"){
            cashAmount.setText(cashAmount.getText()+"9");
        }else if(focusOwner == "cardAmount"){
            cardAmount.setText(cardAmount.getText()+"9");
        }else if(focusOwner == "cardBillNo"){
            cardBillNo.setText(cardBillNo.getText()+"9");
        }else if(focusOwner == "qrAmount"){
            qrAmount.setText(qrAmount.getText()+"9");
        }
        BalanceCalculate();
    }//GEN-LAST:event_myButton8ActionPerformed

    private void myButton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton00ActionPerformed
        // TODO add your handling code here:
        String focusOwner = FocusManager.getCurrentManager().getFocusOwner().getName();
        if(focusOwner == "cashAmount"){
            cashAmount.setText(cashAmount.getText()+"00");
        }else if(focusOwner == "cardAmount"){
            cardAmount.setText(cardAmount.getText()+"00");
        }else if(focusOwner == "cardBillNo"){
            cardBillNo.setText(cardBillNo.getText()+"00");
        }else if(focusOwner == "qrAmount"){
            qrAmount.setText(qrAmount.getText()+"00");
        }
        BalanceCalculate();
    }//GEN-LAST:event_myButton00ActionPerformed

    private void myButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton0ActionPerformed
        // TODO add your handling code here:
        String focusOwner = FocusManager.getCurrentManager().getFocusOwner().getName();
        if(focusOwner == "cashAmount"){
            cashAmount.setText(cashAmount.getText()+"0");
        }else if(focusOwner == "cardAmount"){
            cardAmount.setText(cardAmount.getText()+"0");
        }else if(focusOwner == "cardBillNo"){
            cardBillNo.setText(cardBillNo.getText()+"0");
        }else if(focusOwner == "qrAmount"){
            qrAmount.setText(qrAmount.getText()+"0");
        }
        BalanceCalculate();
    }//GEN-LAST:event_myButton0ActionPerformed

    private void dotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotButtonActionPerformed
        // TODO add your handling code here:
        String focusOwner = FocusManager.getCurrentManager().getFocusOwner().getName();
            
        if((focusOwner == "cashAmount") && (!cashAmount.getText().contains("."))){
            cashAmount.setText(cashAmount.getText()+".");
        }else if((focusOwner == "cardAmount") && (!cardAmount.getText().contains("."))){
            cardAmount.setText(cardAmount.getText()+".");
        }else if((focusOwner == "cardBillNo") && (cardBillNo.getText().contains("."))){
            cardBillNo.setText(cardBillNo.getText()+".");
        }else if((focusOwner == "qrAmount") && (!qrAmount.getText().contains("."))){
            qrAmount.setText(qrAmount.getText()+".");
        }
        BalanceCalculate();
    }//GEN-LAST:event_dotButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        String focusOwner = FocusManager.getCurrentManager().getFocusOwner().getName();
        if(focusOwner == "cashAmount"){
            cashAmount.setText("");
        }else if(focusOwner == "cardAmount"){
            cardAmount.setText("");
        }else if(focusOwner == "cardBillNo"){
            cardBillNo.setText("");
        }else if(focusOwner == "qrAmount"){
            qrAmount.setText("");
        }
        BalanceCalculate();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void backspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceButtonActionPerformed
        // TODO add your handling code here:
        String focusOwner = FocusManager.getCurrentManager().getFocusOwner().getName();
        if((focusOwner == "cashAmount") && (!cashAmount.getText().isEmpty())){
            cashAmount.setText(cashAmount.getText().substring(0, cashAmount.getText().length()-1));
        }else if((focusOwner == "cardAmount") && (!cashAmount.getText().isEmpty())){
            cardAmount.setText(cardAmount.getText().substring(0, cardAmount.getText().length()-1));
        }else if((focusOwner == "cardBillNo") && (!cashAmount.getText().isEmpty())){
            cardBillNo.setText(cardBillNo.getText().substring(0, cardBillNo.getText().length()-1));
        }else if((focusOwner == "qrAmount") && (!cashAmount.getText().isEmpty())){
            qrAmount.setText(qrAmount.getText().substring(0, qrAmount.getText().length()-1));
        }
        BalanceCalculate();
    }//GEN-LAST:event_backspaceButtonActionPerformed

    private void conformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conformActionPerformed
        // TODO add your handling code here:
        
        Date currentDate = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String formattedDate = dateFormat.format(currentDate);
        
        float totalPayAmount = Float.parseFloat(cashAmount.getText().isEmpty() ? "0" : cashAmount.getText()) + Float.parseFloat(cardAmount.getText().isEmpty() ? "0" : cardAmount.getText()) + Float.parseFloat(qrAmount.getText().isEmpty() ? "0" : qrAmount.getText());
        
        try {
            Statement statement = DBconnect.connectToDB().createStatement();
            statement.execute("INSERT INTO PaymentDetails (InvoiceID, Date, SubTotal, Discount, DiscountMethod, PayableAmount, TotalPayAmount, CashPayAmount, CardPayAmount, CardBillNumber, QRPayAmount, Balance, Note) "
                    + "VALUES('"+invoiceNo+"', '"+formattedDate+"', '"+subTotalCal+"', '"+discount+"', '"+discountPercentage+"', '"+payableAmountCal+"', '"+totalPayAmount+"', '"+(cashAmount.getText().isEmpty() ? 0 : cashAmount.getText())+"', '"+(cardAmount.getText().isEmpty() ? 0 : cardAmount.getText())+"', '"+(cardBillNo.getText().isEmpty() ? null : cardBillNo.getText())+"', '"+(qrAmount.getText().isEmpty() ? 0 : qrAmount.getText())+"', '"+balance+"', '')");
            
            statement.execute("UPDATE VehicleDetails SET States = 'Done' WHERE InvoiceNo = '"+invoiceNo+"'");

        } catch (SQLException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.home.ClearSidePane();
        this.dispose();
    }//GEN-LAST:event_conformActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.MyButton backspaceButton;
    private javax.swing.JLabel balanceLable;
    private fosalgo.FTextField cardAmount;
    private fosalgo.FTextField cardBillNo;
    private fosalgo.FTextField cashAmount;
    private button.MyButton clearButton;
    private button.MyButton conform;
    private button.MyButton dotButton;
    private javax.swing.JLabel invoiceID;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private button.MyButton myButton0;
    private button.MyButton myButton00;
    private button.MyButton myButton1;
    private button.MyButton myButton10;
    private button.MyButton myButton2;
    private button.MyButton myButton3;
    private button.MyButton myButton4;
    private button.MyButton myButton5;
    private button.MyButton myButton6;
    private button.MyButton myButton7;
    private button.MyButton myButton8;
    private button.MyButton myButton9;
    private javax.swing.JLabel payableAmount;
    private fosalgo.FTextField qrAmount;
    // End of variables declaration//GEN-END:variables
}
